// Tailwind classes for PlatformAiUsagePage.tsx.
const styles = {
  card: 'gap-6 w-full max-w-full flex flex-col',
  welcome: 'px-9 py-7 gap-8 grid items-center grid-cols-[minmax(0,1fr)_280px] rounded-[24px] [--rule:color-mix(in_srgb,var(--color-primary)_12%,transparent)] [--margin-line:color-mix(in_srgb,var(--color-danger-text)_40%,transparent)] [--margin-x:24px] [background:linear-gradient(90deg,transparent_calc(var(--margin-x)_-_1px),var(--margin-line)_calc(var(--margin-x)_-_1px)_calc(var(--margin-x)_+_1px),transparent_calc(var(--margin-x)_+_1px)),repeating-linear-gradient(180deg,transparent_0_31px,var(--rule)_31px_32px)_0_14px,var(--color-surface)] [box-shadow:0_1px_2px_rgb(21_33_59_/_4%),0_8px_24px_rgb(21_33_59_/_5%)] [&_h1]:m-0 [&_h1]:text-[28px] [&_h1]:leading-[38px] [&_h1]:font-[750] [&_h1]:tracking-[-.035em] [&_h1]:text-ink [@media(max-width:900px)]:grid-cols-[minmax(0,1fr)] [@media(max-width:900px)]:rounded-[20px] [@media(max-width:640px)]:px-4 [@media(max-width:640px)]:py-5 [@media(max-width:640px)]:[&_h1]:text-[22px] [@media(max-width:640px)]:[&_h1]:leading-[30px] [@media(max-width:900px)_and_(width_>_640px)]:p-6',
  welcomeCopy: 'min-w-0 [&>p]:mx-0 [&>p]:mt-2 [&>p]:mb-0 [&>p]:text-[15px] [&>p]:leading-[26px] [&>p]:text-text-secondary',
  nalaWelcome: 'min-h-45 flex flex-col items-center justify-center [@media(max-width:900px)]:gap-3 [@media(max-width:900px)]:min-h-0 [@media(max-width:900px)]:flex-row-reverse [@media(max-width:900px)]:justify-end',
  speech: "mx-0 mt-0 mb-1 px-4.5 py-3 border border-role-border bg-surface relative text-center rounded-[14px] text-ink text-[13px] leading-[20px] font-semibold [box-shadow:0_6px_18px_rgb(21_33_59_/_8%)] [&::after]:bottom-[-5px] [&::after]:left-[calc(50%_-_5px)] [&::after]:w-2.5 [&::after]:h-2.5 [&::after]:border-r [&::after]:border-b [&::after]:border-r-role-border [&::after]:border-b-role-border [&::after]:bg-inherit [&::after]:absolute [&::after]:content-[''] [&::after]:[transform:rotate(45deg)]",
  mascot: 'w-45 h-35 grid relative items-center justify-items-center [@media(max-width:900px)]:w-25 [@media(max-width:900px)]:h-25',
  note: 'm-0 text-[14.5px] leading-[22px] text-text-secondary',
  controls: 'p-1 gap-1.5 w-fit bg-surface-muted flex flex-wrap rounded-[999px] [&_button]:px-4.5 [&_button]:py-1.5 [&_button]:min-h-9.5 [&_button]:border-none [&_button]:bg-transparent [&_button]:[font-style:inherit] [&_button]:cursor-pointer [&_button]:rounded-[999px] [&_button]:text-text-secondary [&_button]:[font-variant:inherit] [&_button]:font-semibold [&_button]:[font-stretch:inherit] [&_button]:text-[13.5px] [&_button]:[line-height:inherit] [&_button]:[font-family:inherit] [&_button]:[transition:background-color_0.15s_ease,color_0.15s_ease,box-shadow_0.15s_ease] [&_button:hover:not([aria-pressed=true])]:bg-paper [&_button:hover:not([aria-pressed=true])]:text-ink [&_button[aria-pressed=true]]:bg-surface [&_button[aria-pressed=true]]:text-primary [&_button[aria-pressed=true]]:[box-shadow:0_2px_8px_rgb(21_33_59_/_10%)] [@media(max-width:640px)]:w-full [@media(max-width:640px)]:[&_button]:px-2.5 [@media(max-width:640px)]:[&_button]:flex-auto [@media(max-width:640px)]:[&_button]:text-center [@media(max-width:640px)]:[&_button]:text-[12.5px]',
  totals: "m-0 gap-4 grid grid-cols-[repeat(auto-fit,minmax(min(100%,200px),1fr))] [&_div]:px-5 [&_div]:py-4.5 [&_div]:border [&_div]:border-role-border [&_div]:bg-surface [&_div]:overflow-hidden [&_div]:relative [&_div]:rounded-[16px] [&_div]:shadow-card [&_div]:[transition:transform_0.15s_ease,box-shadow_0.15s_ease,border-color_0.15s_ease] [&_div::before]:inset-x-0 [&_div::before]:top-0 [&_div::before]:h-[3px] [&_div::before]:absolute [&_div::before]:content-[''] [&_div::before]:[background:linear-gradient(90deg,var(--color-primary),var(--color-accent))] [&_div::before]:opacity-80 [&_div:hover]:border-control-border [&_div:hover]:[transform:translateY(-2px)] [&_div:hover]:[box-shadow:0_8px_24px_rgb(21_33_59_/_8%)] [&_dt]:uppercase [&_dt]:text-[12.5px] [&_dt]:font-bold [&_dt]:text-text-muted [&_dt]:tracking-[0.05em] [&_dd]:mx-0 [&_dd]:mt-1.5 [&_dd]:mb-0 [&_dd]:tabular-nums [&_dd]:text-[26px] [&_dd]:leading-[32px] [&_dd]:font-extrabold [&_dd]:text-ink [&_dd]:tracking-[-0.02em] [@media(max-width:640px)]:gap-3 [@media(max-width:640px)]:grid-cols-[repeat(auto-fit,minmax(140px,1fr))] [@media(max-width:640px)]:[&_div]:px-4 [@media(max-width:640px)]:[&_div]:py-3.5 [@media(max-width:640px)]:[&_dd]:text-[22px] [@media(max-width:640px)]:[&_dd]:leading-[28px]",
  tableRegion: 'w-full border border-role-border bg-surface overflow-x-auto [-webkit-overflow-scrolling:touch] rounded-[16px] shadow-card [&_table]:w-full [&_table]:border-collapse [&_table]:text-[14px] [&_table]:leading-[22px] [&_th]:px-4.5 [&_th]:py-3 [&_th]:border-b [&_th]:border-b-role-border [&_th]:bg-paper [&_th]:text-start [&_th]:whitespace-nowrap [&_th]:uppercase [&_th]:text-[12px] [&_th]:font-bold [&_th]:tracking-[0.05em] [&_th]:text-text-muted [&_td]:px-4.5 [&_td]:py-3.5 [&_td]:border-t [&_td]:border-t-role-border [&_td]:tabular-nums [&_td]:align-middle [&_td]:text-ink [&_tr]:[transition:background-color_0.15s_ease] [&_tbody_tr:hover]:bg-nav-hover [&_code]:px-2 [&_code]:py-[3px] [&_code]:bg-info-bg [&_code]:wrap-anywhere [&_code]:rounded-[6px] [&_code]:text-[13px] [&_code]:text-primary-hover [&_code]:font-semibold',
  usageTableRegion: '[&_table]:min-w-240',
} satisfies Record<string, string>

export default styles
