// Tailwind classes for PlatformReferenceDetailPage.tsx, PlatformReferencesPage.tsx, ReferenceReviewEditor.tsx, ReferenceStages.tsx.
// `platformreferences-*` names carry no styles: they are hooks for the nested selectors in other entries.
const styles = {
  content: 'm-0 p-0 gap-4 w-full min-w-0 max-w-full grid wrap-anywhere [--ease-out:cubic-bezier(.23,1,.32,1)] [--on-accent:#15213B]',
  srOnly: 'w-px h-px overflow-hidden absolute [clip-path:inset(50%)]',
  // Library: stage tabs with counts, then the filters, then the grouped cards.
  library: 'gap-3.5 min-w-0 grid',
  tabs: 'p-1.5 gap-1.5 w-fit max-w-full border border-role-border bg-surface/90 backdrop-blur-sm flex items-center overflow-x-auto rounded-pill [box-shadow:0_1px_3px_rgb(21_33_59_/_4%)] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden [&_button]:py-1.5 [&_button]:pr-2.5 [&_button]:pl-3.5 [&_button]:gap-2 [&_button]:min-h-[38px] [&_button]:border-none [&_button]:bg-transparent [&_button]:inline-flex [&_button]:items-center [&_button]:whitespace-nowrap [&_button]:cursor-pointer [&_button]:rounded-pill [&_button]:text-text-secondary [&_button]:text-[13px] [&_button]:font-semibold [&_button]:[transition:all_160ms_var(--ease-out)] [&_button>span]:px-2 [&_button>span]:py-0.5 [&_button>span]:min-w-5 [&_button>span]:bg-surface-muted [&_button>span]:text-center [&_button>span]:tabular-nums [&_button>span]:rounded-pill [&_button>span]:text-text-secondary [&_button>span]:text-[11.5px] [&_button>span]:font-bold [&_button>span]:[transition:background-color_160ms_ease,color_160ms_ease] [&_button:active]:[transform:scale(.97)] [&_button[aria-pressed=true]]:bg-primary [&_button[aria-pressed=true]]:text-white [&_button[aria-pressed=true]]:[box-shadow:0_2px_8px_rgb(36_71_209_/_25%)] [&_button[aria-pressed=true]>span]:bg-white/20 [&_button[aria-pressed=true]>span]:text-white [&_button[aria-pressed=false]:hover]:bg-nav-hover [&_button[aria-pressed=false]:hover]:text-ink [&_button[data-hot=true][data-group=failed]:not([aria-pressed=true])>span]:bg-danger-bg [&_button[data-hot=true][data-group=failed]:not([aria-pressed=true])>span]:text-danger-text [&_button[data-hot=true][data-group=review]:not([aria-pressed=true])>span:where(:not(&_button[data-hot=true][data-group=failed]>span))]:bg-accent/20 [&_button[data-hot=true][data-group=review]:not([aria-pressed=true])>span:where(:not(&_button[data-hot=true][data-group=failed]>span))]:text-accent-foreground',
  toolbar: 'gap-3 grid items-end grid-cols-[minmax(200px,1fr)_minmax(170px,220px)_auto] [&>button]:py-0 [&>button]:gap-2 [&>button]:h-11 [&>button]:inline-flex [&>button]:items-center [&>button]:justify-center [&>button]:text-[14px] [@media(max-width:1000px)]:grid-cols-2 [@media(max-width:600px)]:grid-cols-[1fr]',
  search: 'px-3.5 py-0 gap-2 min-h-11 border-solid border border-control-border bg-surface flex items-center cursor-text rounded-input text-text-secondary [transition:border-color_160ms_ease,box-shadow_160ms_ease] focus-within:border-primary focus-within:[box-shadow:0_0_0_3px_color-mix(in_srgb,var(--color-primary)_16%,transparent)] [&_input]:px-0 [&_input]:py-2 [&_input]:min-w-0 [&_input]:flex-1 [&_input]:border-none [&_input]:border-0 [&_input]:border-current [&_input]:bg-transparent [&_input]:[font-style:inherit] [&_input]:outline-none [&_input]:text-ink [&_input]:[font-variant:inherit] [&_input]:[font-weight:inherit] [&_input]:[font-stretch:inherit] [&_input]:text-[14px] [&_input]:[line-height:inherit] [&_input]:[font-family:inherit] [&_input::placeholder]:text-text-muted [@media(max-width:1000px)]:col-span-full',
  count: 'm-0 text-[12.5px] leading-[18px] text-text-muted',
  noMatch: 'px-5 py-8 gap-3 border-dashed border border-control-border grid justify-items-center text-center rounded-card [&_p]:m-0',
  bucket: 'mt-1.5 gap-2.5 grid',
  bucketHead: 'gap-y-0.5 gap-x-2.5 flex flex-wrap items-baseline [&_h2]:m-0 [&_h2]:text-[15px] [&_h2]:leading-[22px] [&_h2]:font-[750] [&_h2]:tracking-[-.02em] [&_h2]:text-ink [&_p]:m-0 [&_p]:flex-[1_1_260px] [&_p]:text-[13px] [&_p]:leading-[20px] [&_p]:text-text-muted',
  bucketCount: 'px-[7px] py-0 min-w-5.5 bg-surface-muted text-center tabular-nums rounded-pill text-text-secondary text-[12px] font-bold leading-[20px]',
  // A source card: folded-corner cover, who issued it, where it stands, and the next step. The title link stretches over the whole card.
  cards: 'm-0 p-0 gap-2.5 grid list-none',
  card: 'platformreferences-card px-5 py-4 gap-y-3.5 gap-x-7 border border-role-border bg-surface grid relative items-center grid-cols-[44px_minmax(0,1fr)_264px_150px] rounded-card [transition:border-color_160ms_ease,box-shadow_160ms_ease,transform_160ms_var(--ease-out)] active:[transform:scale(.995)] [@media(hover:hover)_and_(pointer:fine)]:hover:border-control-border [@media(hover:hover)_and_(pointer:fine)]:hover:[box-shadow:0_6px_18px_rgb(21_33_59_/_7%)] motion-safe:data-[fresh=true]:[animation:platformreferences-rise_320ms_var(--ease-out)_both] motion-safe:data-[fresh=true]:[animation-delay:calc(var(--i)_*_45ms)] [@media(max-width:900px)]:gap-y-3 [@media(max-width:900px)]:gap-x-3.5 [@media(max-width:900px)]:grid-cols-[44px_minmax(0,1fr)]',
  cardAction: '[@media(hover:hover)_and_(pointer:fine)]:[.platformreferences-card:hover_&_svg]:[transform:translateX(3px)] [@media(hover:hover)_and_(pointer:fine)]:[.platformreferences-card:hover_&]:border-primary px-3.5 py-0 gap-1.5 min-h-9 border border-control-border inline-flex items-center justify-center whitespace-nowrap [justify-self:end] rounded-pill text-ink text-[13px] font-[650] [transition:border-color_160ms_ease] [&_svg]:[transition:transform_160ms_var(--ease-out)] [.platformreferences-card[data-group=review]_&]:border-primary [.platformreferences-card[data-group=review]_&]:bg-primary [.platformreferences-card[data-group=review]_&]:text-surface [@media(max-width:900px)]:hidden',
  cover: 'mt-0.5 w-11 h-11 grid items-center self-start justify-items-center rounded-[12px] data-[kind=curriculum]:bg-info-bg data-[kind=curriculum]:text-primary data-[kind=guidance]:bg-surface-muted data-[kind=guidance]:text-text-secondary',
  cardMain: 'min-w-0 [&_h3]:m-0 [&_h3]:text-[16px] [&_h3]:leading-[24px] [&_h3]:font-bold [&_h3]:tracking-[-.015em]',
  cardLink: "no-underline text-ink [&::after]:inset-0 [&::after]:absolute [&::after]:content-[''] [&::after]:rounded-card focus-visible:outline-none [&:focus-visible::after]:[outline:2px_solid_var(--color-primary)] [&:focus-visible::after]:outline-offset-[2px]",
  issuer: 'mx-0 mt-0.5 mb-0 gap-y-1 gap-x-2.5 flex flex-wrap items-center text-[13.5px] leading-[20px] text-text-secondary',
  facts: 'mx-0 mt-1.5 mb-0 gap-y-0.5 gap-x-4 flex flex-wrap items-center text-[12.5px] leading-[18px] text-text-muted',
  kind: 'px-[9px] py-0.5 rounded-pill text-[11.5px] font-[650] data-[kind=curriculum]:bg-info-bg data-[kind=curriculum]:text-primary-hover data-[kind=guidance]:bg-surface-muted data-[kind=guidance]:text-text-secondary',
  source: 'gap-1 inline-flex relative items-center underline z-1 text-text-secondary font-semibold decoration-control-border [text-underline-offset:3px] [transition:color_160ms_ease] hover:text-primary hover:decoration-current',
  cause: 'mx-0 mt-2 mb-0 text-[13px] leading-[20px] text-danger-text',
  cardStage: 'gap-2 min-w-0 grid [@media(max-width:900px)]:col-span-full',
  statusLine: 'text-[12.5px] leading-[18px] font-[650] text-text-secondary data-[group=review]:text-warning-text data-[group=failed]:text-danger-text data-[group=published]:text-success-strong [.platformreferences-journeyMeta_&]:text-[14px]',
  // Stage tracker, shared by the cards and the detail page: four nodes joined by a line, labels centred underneath.
  stages: "platformreferences-stages m-0 p-0 grid list-none [--node:20px] [--line:2px] [--track:color-mix(in_srgb,var(--color-control-border)_45%,transparent)] grid-cols-4 [&_li]:gap-1.5 [&_li]:min-w-0 [&_li]:grid [&_li]:relative [&_li]:justify-items-center [&_li+li::before]:top-[calc((var(--node)_-_var(--line))_/_2)] [&_li+li::before]:right-[50%] [&_li+li::before]:w-full [&_li+li::before]:h-[var(--line)] [&_li+li::before]:absolute [&_li+li::before]:content-[''] [&_li+li::before]:rounded-pill [&_li+li::before]:[background:var(--track)] [&_li[data-state=done]+li::before]:bg-primary [&[data-status=published]_li::before]:bg-success-strong [&[data-status=failed]_li+li::before]:[background:color-mix(in_srgb,var(--color-danger-text)_30%,transparent)]",
  stageNode: "w-[var(--node)] h-[var(--node)] [border-width:medium] [border-color:var(--track)] bg-surface grid relative items-center justify-items-center z-1 rounded-[50%] text-surface [.platformreferences-stages_[data-state=done]_&]:border-primary [.platformreferences-stages_[data-state=done]_&]:bg-primary [.platformreferences-stages[data-status=published]_&]:bg-success-strong [.platformreferences-stages_[data-state=now]_&]:text-primary [.platformreferences-stages_[data-state=now]_&::after]:w-2 [.platformreferences-stages_[data-state=now]_&::after]:h-2 [.platformreferences-stages_[data-state=now]_&::after]:bg-current [.platformreferences-stages_[data-state=now]_&::after]:content-[''] [.platformreferences-stages_[data-state=now]_&::after]:rounded-[50%] [.platformreferences-stages[data-status=review]_[data-state=now]_&]:border-accent [.platformreferences-stages[data-status=review]_[data-state=now]_&]:text-accent [.platformreferences-stages[data-status=review]_[data-state=now]_&]:[box-shadow:0_0_0_4px_color-mix(in_srgb,var(--color-accent)_22%,transparent)] [.platformreferences-stages_[data-state=failed]_&]:border-[color-mix(in_srgb,var(--color-danger-text)_55%,transparent)] [.platformreferences-stages_[data-state=now]_&:where(:not(.platformreferences-stages_[data-state=failed]_&))]:border-primary [.platformreferences-stages[data-status=published]_&:where(:not(.platformreferences-stages_[data-state=now]_&)):where(:not(.platformreferences-stages_[data-state=failed]_&)):where(:not(.platformreferences-stages_[data-state=now]_&:where(:not(.platformreferences-stages_[data-state=failed]_&))))]:border-success-strong",
  stageName: 'max-w-full overflow-hidden whitespace-nowrap text-text-muted text-[12px] leading-[16px] font-semibold [text-overflow:ellipsis] [.platformreferences-stages_[data-state=done]_&]:text-text-secondary [.platformreferences-stages_[data-state=now]_&]:text-ink [.platformreferences-stages_[data-state=now]_&]:font-[750] [.platformreferences-stagesLarge_&]:text-[13px] [.platformreferences-stagesLarge_&]:leading-[20px]',
  stagesLarge: 'platformreferences-stagesLarge [--node:28px] [--line:3px]',
  // Upload panel and the other full-width panels on the detail page.
  panel: 'platformreferences-panel px-5.5 py-5 gap-4 min-w-0 border border-role-border bg-surface grid rounded-[16px] shadow-card [&_h2]:m-0 [&_h2]:text-[17px] [&_h2]:leading-[24px] [&_h2]:font-[750] [&_h2]:tracking-[-.02em] [&_h2]:text-ink [&_p]:m-0 [@media(max-width:600px)]:p-4',
  panelHead: '[.platformreferences-panel_&_p]:mt-1 [.platformreferences-panel_&_p]:max-w-[70ch] [.platformreferences-panel_&_p]:text-[13.5px] [.platformreferences-panel_&_p]:leading-[21px]',
  help: '[.platformreferences-panel_&]:mt-2 [.platformreferences-panel_&]:text-[13px] [.platformreferences-panel_&]:leading-[20px] [.platformreferences-panel_&]:text-text-secondary',
  form: 'gap-4 min-w-0 grid',
  fields: 'm-0 p-0 gap-4 min-w-0 border-none grid [&>label]:gap-2.5 [&>label]:min-h-11 [&>label]:flex [&>label]:items-center [&>label]:cursor-pointer [&>label]:font-semibold [&>label_input]:w-4.5 [&>label_input]:h-4.5 [&>label_input]:accent-primary',
  twoColumns: 'gap-3.5 grid grid-cols-2 [@media(max-width:600px)]:grid-cols-[1fr]',
  actions: 'gap-2.5 flex flex-wrap items-center [@media(max-width:600px)]:[&>button]:flex-auto',
  kindChoices: 'm-0 p-0 gap-2.5 min-w-0 border-none grid grid-cols-2 [&_legend]:mb-2 [&_legend]:p-0 [&_legend]:text-[14px] [&_legend]:font-semibold [&_legend]:text-ink [@media(max-width:600px)]:grid-cols-[1fr]',
  kindChoice: 'px-3.5 py-3 gap-3 border-[1.5px] border-control-border bg-surface flex items-start cursor-pointer rounded-card [transition:border-color_160ms_ease,background-color_160ms_ease] [&_input]:mx-0 [&_input]:mt-0.5 [&_input]:mb-0 [&_input]:w-4.5 [&_input]:h-4.5 [&_input]:shrink-0 [&_input]:accent-primary [&_strong]:block [&_strong]:text-[14px] [&_strong]:leading-[22px] [&_strong]:text-ink [&_small]:mt-0.5 [&_small]:block [&_small]:text-[12.5px] [&_small]:leading-[18px] [&_small]:text-text-secondary [&:has(input:checked)]:border-primary [&:has(input:checked)]:bg-info-bg [&:has(input:focus-visible)]:[outline:2px_solid_var(--color-primary)] [&:has(input:focus-visible)]:outline-offset-[2px]',
  drop: 'px-5 py-4.5 gap-4 border-dashed border-2 border-control-border flex items-center cursor-pointer rounded-card [background:color-mix(in_srgb,var(--color-info-bg)_45%,var(--color-surface))] [transition:border-color_160ms_ease,background-color_160ms_ease,transform_160ms_var(--ease-out)] data-[over=true]:border-primary data-[over=true]:[transform:scale(1.005)] data-[filled=true]:border-solid data-[filled=true]:border-primary data-[filled=true]:bg-surface data-[disabled=true]:cursor-not-allowed data-[disabled=true]:opacity-60 focus-within:[outline:2px_solid_var(--color-primary)] focus-within:outline-offset-[2px] [@media(max-width:600px)]:p-3.5 [&[data-over=true]:where(:not(&[data-filled=true]))]:bg-info-bg',
  dropIcon: 'w-12 h-12 shrink-0 border border-role-border bg-surface grid items-center justify-items-center rounded-[50%] text-primary',
  dropText: 'min-w-0 [&_strong]:block [&_strong]:wrap-anywhere [&_strong]:text-[14.5px] [&_strong]:leading-[22px] [&_strong]:text-ink [&_small]:mt-0.5 [&_small]:block [&_small]:text-[12.5px] [&_small]:leading-[18px] [&_small]:text-text-secondary',
  // Detail page: back link, status journey, source viewer.
  back: '-ml-2 pr-3 pl-2 gap-1 w-fit min-h-9 inline-flex items-center no-underline rounded-pill text-text-secondary text-[13.5px] font-semibold [transition:background-color_160ms_ease,color_160ms_ease] [@media(hover:hover)_and_(pointer:fine)]:hover:bg-nav-hover [@media(hover:hover)_and_(pointer:fine)]:hover:text-ink',
  journey: 'px-5.5 py-5 gap-3.5 min-w-0 border border-role-border bg-surface grid rounded-[16px] shadow-card [@media(max-width:600px)]:p-4',
  journeyMeta: 'platformreferences-journeyMeta gap-y-2 gap-x-4 flex flex-wrap items-center text-[13px] leading-[20px] text-text-secondary',
  metaAction: 'ml-auto gap-1.5 inline-flex items-center [@media(max-width:600px)]:ml-0',
  sourceGrid: 'gap-5 grid items-start grid-cols-2 [@media(max-width:1000px)]:grid-cols-[1fr]',
  pdf: 'mt-2.5 w-full h-155 border border-role-border bg-surface-muted block rounded-[12px] [@media(max-width:1000px)]:h-110',
  extracted: 'px-4.5 py-4 gap-2.5 min-w-0 max-h-170 border border-role-border bg-paper overflow-auto grid rounded-[12px] [&_h3]:m-0 [&_h3]:text-[14px] [&_h3]:leading-[20px] [&_label]:gap-2 [&_label]:grid [&_label]:font-semibold [&_select]:p-3 [&_select]:w-full [&_select]:min-h-11 [&_select]:border [&_select]:border-control-border [&_select]:bg-surface [&_select]:[font-style:inherit] [&_select]:rounded-input [&_select]:text-ink [&_select]:[font-variant:inherit] [&_select]:[font-weight:inherit] [&_select]:[font-stretch:inherit] [&_select]:[font-size:inherit] [&_select]:[line-height:inherit] [&_select]:[font-family:inherit] [&_select:focus]:border-primary [&_select:focus]:outline-none [&_select:focus]:[box-shadow:0_0_0_3px_color-mix(in_srgb,var(--color-primary)_16%,transparent)]',
  textField: 'gap-2 grid font-semibold [&_textarea]:p-3 [&_textarea]:w-full [&_textarea]:min-h-11 [&_textarea]:border [&_textarea]:border-control-border [&_textarea]:bg-surface [&_textarea]:[font-style:inherit] [&_textarea]:resize-y [&_textarea]:rounded-input [&_textarea]:text-ink [&_textarea]:[font-variant:inherit] [&_textarea]:font-normal [&_textarea]:[font-stretch:inherit] [&_textarea]:[font-size:inherit] [&_textarea]:[line-height:inherit] [&_textarea]:[font-family:inherit] [&_textarea:focus]:border-primary [&_textarea:focus]:outline-none [&_textarea:focus]:[box-shadow:0_0_0_3px_color-mix(in_srgb,var(--color-primary)_16%,transparent)]',
  sourceText: 'm-0 whitespace-pre-wrap wrap-anywhere text-ink font-reading text-[15px] leading-[1.8]',
  // Review editor: grouped fieldsets, selectable page cards, quiet text areas.
  group: 'platformreferences-group p-4.5 gap-4 min-w-0 border border-role-border grid rounded-[14px] [background:color-mix(in_srgb,var(--color-paper)_55%,var(--color-surface))] [.platformreferences-group_&]:bg-surface [&_legend]:px-2.5 [&_legend]:py-[3px] [&_legend]:bg-info-bg [&_legend]:rounded-pill [&_legend]:text-primary-hover [&_legend]:text-[12.5px] [&_legend]:font-bold [@media(max-width:600px)]:p-3',
  statement: 'pt-4.5 gap-3 [border-top-style:dashed] border-t border-t-control-border grid',
  pageChoices: 'gap-2 max-h-105 grid overflow-y-auto [&_label]:px-3 [&_label]:py-2.5 [&_label]:gap-2.5 [&_label]:border [&_label]:border-role-border [&_label]:flex [&_label]:items-center [&_label]:cursor-pointer [&_label]:rounded-[10px] [&_label]:[transition:border-color_160ms_ease,background-color_160ms_ease] [&_input]:w-4.5 [&_input]:h-4.5 [&_input]:accent-primary [&_label:has(input:checked)]:border-primary [&_label:has(input:checked)]:bg-info-bg [&_label:has(input:disabled)]:cursor-not-allowed [&_label:has(input:disabled)]:text-text-muted',
} satisfies Record<string, string>

export default styles
