// Tailwind classes for NalaLoginMotion.tsx.
// `nalaloginmotion-*` names carry no styles: they are hooks for the nested selectors in other entries.
const styles = {
  scene: 'nalaloginmotion-scene w-full flex relative flex-col items-center [--nala-ease:cubic-bezier(.77,0,.175,1)] [&[data-mood=hello]_[data-nala-part=body]]:[transform-origin:100px_204px] [&[data-mood=hello]_[data-nala-part=body]]:[animation:nalaloginmotion-greet_9s_var(--nala-ease)_infinite] [&[data-mood=hello]_[data-nala-part=left-wing]]:[transform-origin:38px_138px] [&[data-mood=hello]_[data-nala-part=left-wing]]:[animation:nalaloginmotion-wave_9s_var(--nala-ease)_infinite] [&[data-mood=hello]_[data-nala-part=right-wing]]:[transform-origin:162px_138px] [&[data-mood=hello]_[data-nala-part=right-wing]]:[animation:nalaloginmotion-gesture_9s_var(--nala-ease)_infinite] [&[data-mood=hello]_[data-nala-part=eyes]]:[animation:nalaloginmotion-happy-eyes_9s_var(--nala-ease)_infinite] [&[data-mood=hello]_[data-nala-part=smile-eyes]]:[animation:nalaloginmotion-smile_9s_var(--nala-ease)_infinite] [@media(max-width:959px)]:gap-3 [@media(max-width:959px)]:grid [@media(max-width:959px)]:items-center [@media(max-width:959px)]:grid-cols-[108px_minmax(0,1fr)]',
  artwork: 'w-full relative pointer-events-none isolate aspect-[450/360] [@media(max-width:959px)]:w-27 [@media(max-width:959px)]:col-[1] [@media(max-width:959px)]:row-[1] [@media(max-width:959px)]:aspect-[1] [@media(max-width:959px)_and_(min-height:640px)_and_(max-height:800px)]:w-19',
  speech: "mb-1 px-4.5 pt-3 pb-3.5 w-[min(100%,330px)] border-solid border border-border bg-surface relative rounded-[18px] text-ink [&::after]:bottom-[-9px] [&::after]:left-[calc(50%_-_9px)] [&::after]:w-4 [&::after]:h-4 [&::after]:[border-right-style:solid] [&::after]:[border-bottom-style:solid] [&::after]:border-r [&::after]:border-b [&::after]:border-r-border [&::after]:border-b-border [&::after]:bg-surface [&::after]:absolute [&::after]:content-[''] [&::after]:[transform:rotate(45deg)] [@media(max-width:959px)]:m-0 [@media(max-width:959px)]:p-0 [@media(max-width:959px)]:w-full [@media(max-width:959px)]:min-w-0 [@media(max-width:959px)]:border-none [@media(max-width:959px)]:border-0 [@media(max-width:959px)]:border-current [@media(max-width:959px)]:bg-transparent [@media(max-width:959px)]:col-[2] [@media(max-width:959px)]:row-[1] [@media(max-width:959px)]:[&::after]:hidden",
  words: 'm-0 min-h-12.5 relative text-center font-reading text-[18px] leading-[1.4] [@media(max-width:959px)]:min-h-13 [@media(max-width:959px)]:text-start [@media(max-width:959px)]:text-[16px] [@media(max-width:959px)_and_(min-height:640px)_and_(max-height:800px)]:min-h-0 [@media(max-width:959px)_and_(min-height:640px)_and_(max-height:800px)]:text-[14px] [@media(max-width:959px)_and_(min-height:640px)_and_(max-height:800px)]:leading-[1.4]',
  word: 'mr-[.22em] inline-block [animation:nalaloginmotion-word-in_400ms_cubic-bezier(.23,1,.32,1)_both] motion-reduce:[.nalaloginmotion-scene_&]:[animation:none]',
  srOnly: '-m-px p-0 w-px h-px border-none overflow-hidden absolute whitespace-nowrap [clip-path:inset(50%)]',
  trail: 'inset-0 w-full h-full absolute text-primary opacity-14 [@media(max-width:959px)]:hidden',
  character: 'inset-0 grid absolute items-center justify-items-center z-1 [&>svg]:w-[min(78%,340px)] [&>svg]:h-auto [&_[data-nala-part]]:[transform-box:view-box] [&_[data-nala-part=body]]:[transform-origin:100px_166px] [&_[data-nala-part=body]]:[animation:nalaloginmotion-breathe_6s_var(--nala-ease)_infinite] [&_[data-nala-part=face]]:[transform-origin:100px_108px] [&_[data-nala-part=face]]:[animation:nalaloginmotion-nod_9s_var(--nala-ease)_infinite] [&_[data-nala-part=eyes]]:[transform-origin:100px_98px] [&_[data-nala-part=eyes]]:[animation:nalaloginmotion-blink_9s_var(--nala-ease)_infinite] [&_[data-nala-part=brows]]:[transform-origin:100px_65px] [&_[data-nala-part=brows]]:[animation:nalaloginmotion-eyebrows_9s_var(--nala-ease)_infinite] [&_[data-nala-part=cheeks]]:[transform-origin:100px_122px] [&_[data-nala-part=cheeks]]:[animation:nalaloginmotion-blush_9s_var(--nala-ease)_infinite] [&_[data-nala-part=gaze]]:[animation:nalaloginmotion-glance_9s_var(--nala-ease)_infinite] [&_[data-nala-part=mouth]]:[transform-origin:100px_120px] [&_[data-nala-part=mouth]]:[animation:nalaloginmotion-talk_9s_linear_infinite] [&_[data-nala-part=jaw]]:[animation:nalaloginmotion-jaw_9s_linear_infinite] [&_[data-nala-part=shadow]]:[transform-origin:100px_212px] [&_[data-nala-part=shadow]]:[animation:nalaloginmotion-shadow_9s_var(--nala-ease)_infinite] [@media(max-width:959px)]:[&>svg]:w-22 motion-reduce:[.nalaloginmotion-scene_&_[data-nala-part]]:[animation:none] [@media(max-width:959px)_and_(min-height:640px)_and_(max-height:800px)]:[&>svg]:w-15.5',
  object: 'h-auto absolute z-2 [animation:nalaloginmotion-drift_8s_var(--nala-ease)_infinite] motion-reduce:[.nalaloginmotion-scene_&]:[animation:none]',
  book: 'top-[22%] left-[3%] w-[16%] [rotate:-14deg] [@media(max-width:959px)]:left-0 [@media(max-width:959px)]:w-[22%]',
  bulb: 'top-[10%] right-[6%] w-[12%] [rotate:12deg] [animation-delay:-3s] [@media(max-width:959px)]:right-0 [@media(max-width:959px)]:w-[18%]',
  pencil: 'right-[4%] bottom-[15%] w-[7%] [rotate:20deg] [animation-duration:7s] [animation-delay:-2s] [@media(max-width:959px)]:hidden',
  atom: 'bottom-[13%] left-[4%] w-[14%] text-primary [rotate:-10deg] [animation-duration:9s] [animation-delay:-5s] [@media(max-width:959px)]:hidden',
  question: 'top-[2%] right-[31%] w-[8%] text-primary [rotate:10deg] [animation-delay:-6s] [@media(max-width:959px)]:hidden',
  spark: 'top-[8%] left-[28%] w-[6%] text-accent [animation:nalaloginmotion-twinkle_5s_var(--nala-ease)_-1s_infinite] [@media(max-width:959px)]:hidden',
} satisfies Record<string, string>

export default styles
