// Tailwind classes for ParentHomePage.tsx.
const styles = {
  content: 'mx-auto gap-6 max-w-280 grid [&_:is(a,_button):focus-visible]:[outline:2px_solid_var(--color-primary)] [&_:is(a,_button):focus-visible]:outline-offset-[3px]',
  hero: 'px-10 py-7 gap-6 grid items-center grid-cols-[minmax(0,1fr)_260px] rounded-[24px] [--rule:color-mix(in_srgb,var(--color-primary)_12%,transparent)] [--margin-line:color-mix(in_srgb,var(--color-danger-text)_40%,transparent)] [--margin-x:24px] [background:linear-gradient(90deg,transparent_calc(var(--margin-x)_-_1px),var(--margin-line)_calc(var(--margin-x)_-_1px)_calc(var(--margin-x)_+_1px),transparent_calc(var(--margin-x)_+_1px)),repeating-linear-gradient(180deg,transparent_0_31px,var(--rule)_31px_32px)_0_14px,var(--color-surface)] [box-shadow:0_1px_2px_rgb(21_33_59_/_4%),0_8px_24px_rgb(21_33_59_/_5%)] [animation:parenthome-rise_460ms_cubic-bezier(.23,1,.32,1)_both] [&_h1]:m-0 [&_h1]:wrap-anywhere [&_h1]:text-[32px] [&_h1]:leading-[42px] [&_h1]:font-[750] [&_h1]:tracking-[-.035em] max-lg:px-7 max-lg:py-6 max-lg:grid-cols-[minmax(0,1fr)_200px] max-md:px-5 max-md:py-6 max-md:gap-4 max-md:[--margin-x:10px] max-md:grid-cols-[minmax(0,1fr)] max-md:rounded-[20px] max-md:[&_h1]:text-[28px] max-md:[&_h1]:leading-[36px] motion-reduce:[animation:none]',
  heroCopy: 'min-w-0',
  school: 'mx-0 mt-1 mb-0 text-[14px] leading-[22px] text-text-secondary',
  story: 'mx-0 mt-4 mb-0 max-w-[46ch] text-pretty text-[17px] leading-[28px] text-ink [&_strong]:font-bold max-md:text-[16px] max-md:leading-[26px]',
  released: 'mx-0 mt-4 mb-0 gap-1.5 inline-flex items-center text-[13px] leading-[20px] font-semibold text-success-strong',
  nala: 'flex flex-col items-center max-md:gap-2 max-md:flex-row-reverse max-md:[justify-content:start]',
  speech: "m-0 px-4 py-2.5 border border-role-border bg-surface relative text-center rounded-[14px] text-ink text-[13px] leading-[20px] font-[550] [box-shadow:0_6px_18px_rgb(21_33_59_/_8%)] [&::after]:bottom-[-5px] [&::after]:left-[calc(50%_-_5px)] [&::after]:w-2.5 [&::after]:h-2.5 [&::after]:bg-inherit [&::after]:absolute [&::after]:content-[''] [&::after]:rounded-[2px] [&::after]:[transform:rotate(45deg)] max-md:max-w-[22ch] max-md:text-start max-md:[&::after]:top-[calc(50%_-_5px)] max-md:[&::after]:bottom-auto max-md:[&::after]:-left-1",
  perch: 'w-50 h-40 grid relative items-center justify-items-center [&>svg]:relative max-lg:w-40 max-lg:[&>svg]:w-35 max-lg:[&>svg]:h-auto max-md:w-24 max-md:h-24 max-md:flex-none max-md:[&>svg]:w-26',
  loading: 'm-0 text-[14px] font-semibold text-primary-hover',
  skeleton: 'gap-4 grid [&_span]:h-35 [&_span]:bg-surface-muted [&_span]:block [&_span]:rounded-[24px] max-md:[&_span]:rounded-[20px]',
  plain: 'p-8 bg-surface rounded-[24px] [&_h2]:m-0 [&_h2]:text-[18px] [&_h2]:leading-[26px] [&_h2]:font-[650] [&_h2]:tracking-[-.02em] [&_p]:mx-0 [&_p]:mt-2 [&_p]:mb-0 [&_p]:max-w-[52ch] [&_p]:text-[15px] [&_p]:leading-[24px] [&_p]:text-text-secondary max-md:px-5 max-md:py-6 max-md:rounded-[20px]',
  grid: 'gap-6 grid items-start grid-cols-[minmax(0,1.55fr)_minmax(280px,1fr)] max-lg:grid-cols-[minmax(0,1fr)]',
  main: 'gap-6 min-w-0 grid',
  side: 'gap-6 min-w-0 grid [&>section:last-child]:[animation:parenthome-rise_460ms_cubic-bezier(.23,1,.32,1)_both] [&>section:last-child]:[animation-delay:210ms] motion-reduce:[&>section:last-child]:[animation:none]',
  letter: 'px-8 py-7 min-w-0 bg-surface rounded-[24px] [animation:parenthome-rise_460ms_cubic-bezier(.23,1,.32,1)_both] [animation-delay:70ms] [&_h2]:m-0 [&_h2]:gap-2 [&_h2]:flex [&_h2]:items-center [&_h2]:text-[15px] [&_h2]:leading-[24px] [&_h2]:font-[650] [&_h2]:text-text-secondary [&_h2_svg]:text-primary [&_h3]:mx-0 [&_h3]:mt-4 [&_h3]:mb-0 [&_h3]:text-balance [&_h3]:text-[22px] [&_h3]:leading-[30px] [&_h3]:font-bold [&_h3]:tracking-[-.025em] [&>a]:mt-6 [&>a]:px-5 [&>a]:min-h-12 [&>a]:rounded-pill [&>a]:text-[14px] [&>a]:font-[650] max-md:px-5 max-md:py-6 max-md:rounded-[20px] max-md:[&_h3]:text-[20px] max-md:[&_h3]:leading-[28px] max-md:[&>a]:w-full max-md:[&>a]:justify-center motion-reduce:[animation:none]',
  concepts: 'px-8 py-7 gap-5 min-w-0 bg-surface grid rounded-[24px] [animation:parenthome-rise_460ms_cubic-bezier(.23,1,.32,1)_both] [animation-delay:140ms] [&_h2]:m-0 [&_h2]:gap-2 [&_h2]:flex [&_h2]:items-center [&_h2]:text-[15px] [&_h2]:leading-[24px] [&_h2]:font-[650] [&_h2]:text-text-secondary [&_h2_svg]:text-primary [&_h3]:mx-0 [&_h3]:mt-0 [&_h3]:mb-2 [&_h3]:text-[14px] [&_h3]:leading-[20px] [&_h3]:font-[650] max-md:px-5 max-md:py-6 max-md:rounded-[20px] motion-reduce:[animation:none]',
  earlier: 'px-8 py-7 min-w-0 bg-surface rounded-[24px] [animation:parenthome-rise_460ms_cubic-bezier(.23,1,.32,1)_both] [animation-delay:280ms] [&_h2]:m-0 [&_h2]:text-[17px] [&_h2]:leading-[24px] [&_h2]:font-[650] [&_h2]:tracking-[-.02em] [&_ul]:mx-0 [&_ul]:mt-2 [&_ul]:mb-0 [&_ul]:p-0 [&_ul]:list-none [&_li]:py-5 [&_li+li]:border-t [&_li+li]:border-t-role-border [&_li:last-child]:pb-0 [&_h3]:m-0 [&_h3]:text-[16px] [&_h3]:leading-[24px] [&_h3]:font-[650] [&_h3]:tracking-[-.02em] max-md:px-5 max-md:py-6 max-md:rounded-[20px] motion-reduce:[animation:none]',
  fresh: 'ml-2 px-2.5 py-0.5 bg-success-bg inline-block align-middle rounded-pill text-success-strong text-[12px] leading-[18px] font-[650] tracking-[0]',
  date: 'mx-0 mt-1 mb-0 text-[13px] leading-[20px] text-text-muted',
  text: 'mt-4 max-w-[62ch] [&_p]:m-0 [&_p]:text-pretty [&_p]:wrap-anywhere [&_p]:text-[16px] [&_p]:leading-[28px] [&_p]:text-ink [&_p+p]:mt-3',
  hint: 'mx-0 -mt-1 mb-2 text-[13px] leading-[20px] text-text-secondary',
  chips: 'm-0 p-0 gap-2 flex flex-wrap list-none [&_li]:py-1.5 [&_li]:pr-3.5 [&_li]:pl-2.5 [&_li]:gap-1.5 [&_li]:min-h-9 [&_li]:inline-flex [&_li]:items-center [&_li]:wrap-anywhere [&_li]:rounded-pill [&_li]:text-[14px] [&_li]:leading-[20px] [&_li]:font-semibold [&[data-status=done]_li]:bg-success-bg [&[data-status=done]_li]:text-success-strong [&[data-status=growing]_li]:bg-warning-bg [&[data-status=growing]_li]:text-warning-text',
} satisfies Record<string, string>

export default styles
