// Tailwind classes for SchoolImportPage.tsx, ImportSteps.tsx, ImportColumnGuide.tsx, ImportResult.tsx and ImportHistory.tsx.
// Phones reflow both tables into labeled entries below `md`; nothing here scrolls sideways.
const styles = {
  content: 'mx-auto grid w-full max-w-280 gap-6',
  head: 'flex flex-wrap items-end justify-between gap-x-6 gap-y-3',
  headText: 'min-w-0 flex-[1_1_320px]',
  title: 'm-0 text-[28px] leading-9 font-bold tracking-[-.03em] text-balance text-ink max-md:text-[24px] max-md:leading-8',
  lead: 'm-0 mt-1 max-w-[62ch] text-[14px] leading-6 text-pretty text-text-secondary',
  template: 'inline-flex min-h-11 items-center gap-2 rounded-button border border-control-border bg-surface px-4 text-[14px] font-bold text-ink no-underline transition-[background-color,transform] duration-160 hover:bg-surface-muted active:translate-y-px motion-reduce:transition-none motion-reduce:active:translate-y-0',

  // Where the admin is: choose the file, wait for the check, read the result.
  steps: 'm-0 flex list-none flex-wrap items-center gap-y-2 p-0 text-[13px] font-semibold',
  stepItem: 'flex items-center gap-2 not-last:after:mr-2 not-last:after:h-px not-last:after:w-6 not-last:after:bg-control-border/40 not-last:after:content-[""] max-sm:gap-1 max-sm:not-last:after:mr-1 max-sm:not-last:after:w-3',
  step: 'inline-flex min-h-8 items-center gap-1.5 rounded-pill px-3 transition-colors duration-160 data-[state=current]:bg-ink data-[state=current]:text-surface data-[state=done]:text-success-strong data-[state=next]:text-text-muted motion-reduce:transition-none max-sm:px-2.5',

  // Upload: one white workspace beside a warm reference panel.
  layout: 'grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_340px]',
  main: 'grid min-w-0 content-start gap-6',
  workspace: 'grid min-w-0 gap-5 rounded-[20px] border border-role-border bg-surface p-6 max-sm:p-4',
  yearField: 'max-w-sm',
  bar: 'flex flex-wrap items-center justify-between gap-x-4 gap-y-3 border-t border-role-border pt-5',
  barText: 'm-0 min-w-0 flex-[1_1_220px] text-[13px] leading-5 text-text-secondary',
  submit: 'max-sm:w-full',

  guide: 'grid min-w-0 gap-5 rounded-[20px] bg-paper p-5',
  guideTitle: 'm-0 text-[15px] leading-6 font-bold text-ink',
  guideLead: 'm-0 -mt-3 text-[13px] leading-5 text-text-secondary',
  group: 'grid gap-2',
  groupTitle: 'm-0 text-[13px] leading-5 font-bold text-ink',
  groupNote: 'm-0 text-[12.5px] leading-[18px] text-text-secondary',
  columns: 'm-0 grid gap-1.5',
  column: 'grid grid-cols-[6.75rem_minmax(0,1fr)] items-baseline gap-x-3',
  code: 'justify-self-start rounded-lg border border-role-border bg-surface px-2 py-0.5 font-mono text-[12px] leading-5 text-ink',
  rule: 'm-0 text-[13px] leading-5 text-text-secondary',
  after: 'grid gap-2 border-l-2 border-accent/55 pl-4',
  afterList: 'm-0 grid list-none gap-1.5 p-0 text-[13px] leading-5 text-text-secondary',

  // Result: one panel, sections divided by hairlines (no card inside a card).
  panel: 'min-w-0 overflow-hidden rounded-[20px] border border-role-border bg-surface animate-file-in motion-reduce:animate-none',
  verdict: 'grid grid-cols-[auto_minmax(0,1fr)] items-center gap-x-5 gap-y-3 p-6 max-sm:grid-cols-1 max-sm:p-4',
  halo: 'relative grid h-26 w-28 shrink-0 place-items-center before:absolute before:bottom-1 before:size-22 before:rounded-full before:bg-accent/30 before:content-[""] [&>svg]:relative max-sm:h-20 max-sm:w-24 max-sm:before:size-16',
  verdictTitle: 'm-0 text-[20px] leading-7 font-bold tracking-[-.02em] text-balance text-ink',
  verdictText: 'm-0 mt-1 max-w-[60ch] text-[14px] leading-6 text-pretty text-text-secondary',
  verdictActions: 'mt-4 flex flex-wrap items-center gap-2 max-sm:flex-col max-sm:items-stretch',
  counts: 'm-0 grid grid-cols-3 divide-x divide-role-border border-t border-role-border',
  count: 'min-w-0 px-6 py-4 max-sm:px-3',
  countLabel: 'text-[13px] leading-5 text-text-secondary',
  countValue: 'm-0 mt-0.5 text-[28px] leading-9 font-bold tracking-[-.02em] text-ink tabular-nums max-sm:text-[24px] data-[tone=success]:text-success-strong data-[tone=danger]:text-danger-text',
  errors: 'border-t border-role-border',
  errorsTitle: 'm-0 px-6 pt-5 pb-3 text-[15px] leading-6 font-bold text-ink max-sm:px-4',
  region: 'max-h-105 overflow-auto',
  table: 'w-full border-collapse text-[14px] max-sm:block max-sm:[&_tbody]:block',
  thead: 'max-sm:sr-only',
  th: 'sticky top-0 border-y border-role-border bg-canvas px-6 py-2.5 text-start text-[12.5px] font-semibold text-text-secondary',
  errRow: 'max-sm:grid max-sm:grid-cols-[auto_minmax(0,1fr)] max-sm:items-baseline max-sm:gap-x-3 max-sm:gap-y-1 max-sm:border-t max-sm:border-surface-muted max-sm:px-4 max-sm:py-3',
  errCell: 'border-t border-surface-muted px-6 py-3 align-top wrap-anywhere tabular-nums max-sm:border-0 max-sm:p-0',
  errRowNumber: 'w-24 whitespace-nowrap font-semibold max-sm:before:content-["Baris_"]',
  errField: 'w-56 max-sm:w-auto',
  errMessage: 'max-sm:col-span-2',

  // History.
  history: 'min-w-0 overflow-hidden rounded-[20px] border border-role-border bg-surface',
  historyHead: 'flex items-baseline justify-between gap-3 px-6 pt-5 pb-3 max-sm:px-4',
  historyTitle: 'm-0 text-[17px] leading-6 font-bold tracking-[-.01em] text-ink',
  total: 'm-0 text-[13px] text-text-muted',
  empty: 'm-0 px-6 pt-4 pb-10 text-center text-[14px] leading-6 text-text-secondary',
  skeleton: 'mx-6 mb-6 grid gap-2 max-sm:mx-4',
  skeletonRow: 'h-11 rounded-[10px] bg-surface-muted animate-loader-pulse motion-reduce:animate-none',
  more: 'm-6 mt-4',
  htable: 'w-full border-collapse text-[14px] max-md:block max-md:[&_tbody]:block',
  hthead: 'max-md:sr-only',
  hRow: 'max-md:grid max-md:grid-cols-[minmax(0,1fr)_auto] max-md:items-center max-md:gap-x-3 max-md:gap-y-1.5 max-md:border-t max-md:border-surface-muted max-md:px-4 max-md:py-4',
  hCell: 'border-t border-surface-muted px-6 py-3 align-middle max-md:border-0 max-md:p-0 max-md:before:mr-2 max-md:before:text-[13px] max-md:before:text-text-muted max-md:before:content-[attr(data-label)]',
  hTime: 'font-semibold whitespace-nowrap max-md:order-1 max-md:before:content-none',
  hStatus: 'max-md:order-2 max-md:justify-self-end max-md:before:content-none',
  hYear: 'whitespace-nowrap max-md:order-3 max-md:col-span-2 max-md:grid max-md:grid-cols-[6.5rem_minmax(0,1fr)]',
  hResult: 'max-md:order-4 max-md:col-span-2 max-md:grid max-md:grid-cols-[6.5rem_minmax(0,1fr)]',
  hActions: 'whitespace-nowrap max-md:order-5 max-md:col-span-2 max-md:before:content-none',
  results: 'flex flex-wrap gap-x-2.5 gap-y-0.5',
  ok: 'font-semibold text-success-strong',
  bad: 'font-semibold text-danger-text',
  muted: 'text-text-muted',
  badge: 'inline-flex items-center rounded-pill px-2.5 py-1 text-[12px] leading-[1.4] font-semibold whitespace-nowrap data-[tone=done]:bg-success-bg data-[tone=done]:text-success-strong data-[tone=partial]:bg-warning-bg data-[tone=partial]:text-warning-text data-[tone=failed]:bg-danger-bg data-[tone=failed]:text-danger-text data-[tone=working]:bg-info-bg data-[tone=working]:text-primary-hover',
  view: 'inline-flex min-h-11 items-center rounded-button px-3 text-[14px] font-bold text-primary-hover no-underline hover:bg-nav-hover',
  compact: 'min-h-11 px-3 text-[13px]',
} satisfies Record<string, string>

export default styles
