// Tailwind classes for ImportHistory.tsx, SchoolImportPage.tsx, SchoolInvitationsPage.tsx.
// `schoolimport-*` names carry no styles: they are hooks for the nested selectors in other entries.
const styles = {
  content: 'w-full max-w-full [&_h1]:m-0 [&_h1]:text-[22px] [&_h1]:leading-[30px]',
  steps: 'mx-0 mt-6 mb-4 p-0 gap-2 flex flex-wrap list-none [&_li]:px-3.5 [&_li]:py-2 [&_li]:gap-2 [&_li]:bg-surface-muted [&_li]:flex [&_li]:items-center [&_li]:rounded-[999px] [&_li]:text-[14px] [&_li]:font-semibold [&_li[aria-current]]:bg-ink [&_li[aria-current]]:text-surface [&_li_span]:text-[12px]',
  note: 'mx-0 my-4 text-text-secondary text-[13px] leading-[21px]',
  grid: 'mt-6 gap-6 grid items-start grid-cols-[repeat(auto-fit,minmax(min(100%,360px),1fr))] [@media(max-width:768px)]:mt-4 [@media(max-width:768px)]:gap-4',
  card: 'schoolimport-card p-5 min-w-0 border border-role-border bg-surface rounded-[14px] [&_h2]:m-0 [&_h2]:text-[15px] [@media(max-width:480px)]:p-3.5 [@media(max-width:768px)_and_(width_>_480px)]:p-4',
  dropzone: 'px-6 py-8 gap-3 bg-paper flex flex-col items-center text-center rounded-[20px] [&>svg]:text-primary [&>span]:text-text-muted [&>span]:text-[14px] [&>div]:w-full [&>div]:text-start [&_input]:p-2 [&_input]:w-full [&_input]:min-w-0 [&_input]:text-[14px] [@media(max-width:480px)]:px-3 [@media(max-width:480px)]:py-6',
  file: 'my-4 p-4 gap-4 bg-info-bg flex items-center rounded-[16px] [&_span]:min-w-0 [&_span]:wrap-anywhere [&_strong]:block [&_strong]:text-[15px] [&_small]:mt-1 [&_small]:block [&_small]:text-[13px] [&_small]:text-text-secondary',
  actions: 'mt-6 gap-3 flex flex-wrap',
  cardHeading: 'gap-3 flex flex-wrap items-center justify-between',
  download: 'min-h-11 inline-flex items-center text-[14px] font-semibold',
  columns: 'mx-0 mt-4 mb-0 gap-3 grid [&_div]:gap-3 [&_div]:grid [&_div]:grid-cols-[120px_minmax(0,1fr)] [&_div]:text-[14px] [&_code]:text-[13px] [&_dd]:m-0 [&_dd]:text-text-secondary [@media(max-width:480px)]:[&_div]:grid-cols-[90px_minmax(0,1fr)]',
  preview: 'mt-8 [&_h2]:text-[20px]',
  filename: 'wrap-anywhere text-text-secondary',
  summary: 'gap-4 grid grid-cols-[repeat(auto-fit,minmax(min(100%,200px),1fr))] [&_div]:px-6 [&_div]:py-5 [&_div]:border [&_div]:border-role-border [&_div]:bg-surface [&_div]:rounded-[14px] [&_span]:block [&_span]:text-[14px] [&_span]:text-text-secondary [&_strong]:mt-1 [&_strong]:block [&_strong]:text-[32px] [@media(max-width:768px)]:gap-3 [@media(max-width:768px)]:grid-cols-[repeat(auto-fit,minmax(130px,1fr))] [@media(max-width:768px)]:[&_div]:px-4 [@media(max-width:768px)]:[&_div]:py-3.5 [@media(max-width:768px)]:[&_strong]:text-[24px]',
  tableRegion: 'schoolimport-tableRegion w-full border border-role-border bg-surface overflow-auto [-webkit-overflow-scrolling:touch] rounded-[14px] [&_table]:w-full [&_table]:min-w-185 [&_table]:border-collapse [&_table]:table-fixed [&_table]:text-[14px] [&_caption]:p-4 [&_caption]:text-start [&_caption]:font-semibold [&_th]:px-4 [&_th]:py-3 [&_th]:border-t [&_th]:border-t-surface-muted [&_th]:text-start [&_th]:wrap-anywhere [&_th]:align-top [&_th]:text-[13px] [&_th]:text-text-secondary [&_th:first-child]:w-20 [&_th:last-child]:w-[28%] [&_td]:px-4 [&_td]:py-3 [&_td]:border-t [&_td]:border-t-surface-muted [&_td]:wrap-anywhere [&_td]:align-top [&_td_span]:mt-1 [&_td_span]:block [&_td_strong]:mt-1 [&_td_strong]:block [&_ul]:m-0 [&_ul]:pl-4 [&_ul]:text-danger-text',
  processing: 'my-6 p-6 border border-role-border bg-surface rounded-[14px] [&_h2]:mt-0',
  scenario: `[&_select]:py-2.5 [&_select]:pr-10.5 [&_select]:pl-3.5 [&_select]:w-full [&_select]:min-w-0 [&_select]:min-h-11 [&_select]:border [&_select]:border-control-border [&_select]:bg-surface [&_select]:[background-image:url("data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20width='16'%20height='16'%20viewBox='0%200%2024%2024'%20fill='none'%20stroke='%23475467'%20stroke-width='2'%20stroke-linecap='round'%20stroke-linejoin='round'%3E%3Cpath%20d='m6%209%206%206%206-6'/%3E%3C/svg%3E")] [&_select]:[background-position:right_14px_center] [&_select]:[background-size:16px] [&_select]:[background-repeat:no-repeat] [&_select]:[font-style:inherit] [&_select]:cursor-pointer [&_select]:rounded-[12px] [&_select]:[font-variant:inherit] [&_select]:[font-weight:inherit] [&_select]:[font-stretch:inherit] [&_select]:[font-size:inherit] [&_select]:[line-height:inherit] [&_select]:[font-family:inherit] [&_select]:text-ink [&_select]:[appearance:none] [&_select]:[-webkit-appearance:none] [&_select]:[transition:border-color_0.15s_ease,box-shadow_0.15s_ease] [:root[data-theme=dark]_&_select]:[background-image:url("data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20width='16'%20height='16'%20viewBox='0%200%2024%2024'%20fill='none'%20stroke='%2394A3B8'%20stroke-width='2'%20stroke-linecap='round'%20stroke-linejoin='round'%3E%3Cpath%20d='m6%209%206%206%206-6'/%3E%3C/svg%3E")] [&_select:focus]:border-primary [&_select:focus]:outline-none [&_select:focus]:[box-shadow:0_0_0_3px_rgba(36,71,209,0.14)]`,
  resultMark: 'w-12 h-12 bg-success-bg grid items-center justify-items-center rounded-[14px] text-success-strong text-[24px]',
  resultTitle: '[.schoolimport-card_&]:mx-0 [.schoolimport-card_&]:mt-5 [.schoolimport-card_&]:mb-0 [.schoolimport-card_&]:text-[22px]',
  resultCounts: 'mt-5 gap-3 grid [&_div]:gap-4 [&_div]:flex [&_div]:justify-between [&_div]:text-[15px] [&_dt]:text-text-secondary [&_dd]:m-0 [&_dd]:font-semibold',
  parentList: 'p-5 gap-4 bg-paper grid list-none rounded-[16px] [&_li]:min-w-0 [&_li]:wrap-anywhere [&_span]:mt-1 [&_span]:block [&_span]:text-[14px] [&_span]:text-text-secondary',
  heading: 'pt-2 pb-4 gap-5 flex flex-wrap items-center justify-between [&>div:first-child]:min-w-0 [&>div:first-child]:flex-[1_1_280px] [&_h1]:m-0 [&_h1]:text-[28px] [&_h1]:leading-[36px] [&_h1]:font-bold [&_h1]:tracking-[-0.03em] [@media(max-width:768px)]:[&_h1]:text-[24px] [@media(max-width:768px)]:[&_h1]:leading-[32px]',
  invitationsTable: '[.schoolimport-tableRegion_&]:w-full [.schoolimport-tableRegion_&]:min-w-full [.schoolimport-tableRegion_&]:table-auto [.schoolimport-tableRegion_&_th:first-child]:w-auto [.schoolimport-tableRegion_&_th:first-child]:min-w-35 [.schoolimport-tableRegion_&_th:nth-child(2)]:w-auto [.schoolimport-tableRegion_&_th:last-child]:w-auto [.schoolimport-tableRegion_&_th:last-child]:min-w-35 [.schoolimport-tableRegion_&_th:nth-child(2):where(:not(.schoolimport-tableRegion_&_th:last-child))]:min-w-22.5',
  personCell: 'gap-3 min-w-0 flex items-center',
  avatar: 'w-9.5 h-9.5 shrink-0 overflow-visible flex items-center justify-center rounded-[50%] [background:var(--color-paper,#f0f4ff)]',
  invitationName: 'whitespace-nowrap font-semibold text-ink',
  statusBadge: 'px-2.5 py-1 bg-surface-muted inline-flex items-center whitespace-nowrap rounded-[999px] text-[12px] font-semibold leading-[1.4] text-text-secondary',
  status_activated: 'bg-success-bg text-success-strong',
  status_active: 'bg-success-bg text-success-strong',
  status_sent: 'bg-info-bg text-primary-hover',
  status_pending: 'bg-info-bg text-primary-hover',
  status_failed: 'bg-danger-bg text-danger-text',
  status_expired: 'bg-danger-bg text-danger-text',
  status_requires_assistance: '[background:var(--color-warning-bg,#fffbeb)] [color:var(--color-warning-text,#b45309)]',
} satisfies Record<string, string>

export default styles
