import { expect, test } from '@playwright/test'

test('onboarding review validates, simulates confirmation and restores mobile keyboard focus', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 375, height: 800 })
  await page.goto('/review/platform/schools')
  const trigger = page.getByRole('button', { name: 'Daftarkan sekolah' })
  await trigger.focus()
  await page.keyboard.press('Enter')
  const dialog = page.getByRole('dialog', { name: 'Daftarkan sekolah' })
  await dialog.getByRole('button', { name: 'Simulasikan undangan' }).click()
  await expect(dialog.getByRole('textbox', { name: 'Nama sekolah' })).toBeFocused()
  await dialog.getByRole('textbox', { name: 'Nama sekolah' }).fill('Sekolah Contoh dengan Nama Panjang untuk Pratinjau Pendaftaran')
  await dialog.getByRole('textbox', { name: 'NPSN' }).fill('00123456')
  await dialog.getByRole('textbox', { name: 'Email admin sekolah pertama' }).fill('operator@example.test')
  expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false)
  expect(await dialog.evaluate((element) => element.scrollWidth > element.clientWidth)).toBe(false)
  await page.screenshot({ path: testInfo.outputPath('onboarding-375.png'), fullPage: true })
  await dialog.getByRole('button', { name: 'Simulasikan undangan' }).click()
  await expect(dialog.getByRole('button', { name: /Menyiapkan simulasi/ })).toBeDisabled()
  await expect(dialog).toContainText('Simulasi pendaftaran selesai')
  await expect(dialog).toContainText('00123456')
  await dialog.press('Escape')
  await expect(dialog).not.toBeVisible()
  await expect(trigger).toBeFocused()
})

test('review school pages retain cursor for detail and reset it on search', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 700 })
  await page.goto('/review/platform/schools')
  await expect(page.getByRole('link', { name: 'SMPN 5 Yogyakarta' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'SMPN 3 Bantul' })).toHaveCount(0)

  await page.getByRole('button', { name: 'Halaman berikutnya' }).click()
  await expect(page.getByRole('link', { name: 'SMPN 3 Bantul' })).toBeVisible()
  await page.getByRole('link', { name: 'SMPN 3 Bantul' }).click()
  await expect(page.getByRole('dialog', { name: 'SMPN 3 Bantul' })).toBeVisible()
  await page.getByRole('dialog', { name: 'SMPN 3 Bantul' }).press('Escape')

  await page.getByRole('textbox', { name: 'Cari sekolah' }).fill('Sleman')
  await expect(page).not.toHaveURL(/cursor=/)
  await expect(page.getByRole('link', { name: 'SMP Muhammadiyah 2' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'SMPN 3 Bantul' })).toHaveCount(0)
  const hasOverflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)
  expect(hasOverflow).toBe(false)
})

test('school actions support the keyboard and long names reflow', async ({ page }) => {
  await page.goto('/review/platform/schools')
  const school = page.getByRole('link', { name: 'SMPN 5 Yogyakarta' })
  await school.focus()
  await page.keyboard.press('Tab')
  const menu = page.getByRole('button', { name: 'Tindakan SMPN 5 Yogyakarta' })
  await expect(menu).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('button', { name: 'Ganti admin sekolah' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(menu).toBeFocused()
  await expect(page.getByRole('button', { name: 'Ganti admin sekolah' })).toHaveCount(0)

  await school.evaluate((link) => { link.textContent = 'Sekolah Menengah Pertama dengan Nama Resmi Sangat Panjang TanpaSingkatanDanTanpaSpasiTambahan'.repeat(2) })
  for (const width of [320, 768, 1440]) {
    await page.setViewportSize({ width, height: 800 })
    const hasOverflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)
    expect(hasOverflow, `horizontal overflow at ${width}px`).toBe(false)
  }
})

test('school suspension confirms a reversible simulation and restores mobile focus', async ({ page }, testInfo) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.setViewportSize({ width: 320, height: 700 })
  await page.goto('/review/platform/schools')
  await page.getByRole('button', { name: 'Tindakan SMPN 5 Yogyakarta' }).click()
  const trigger = page.getByRole('button', { name: 'Tangguhkan' })
  await trigger.click()
  const suspension = page.getByRole('dialog', { name: 'Tangguhkan SMPN 5 Yogyakarta?' })
  await expect(suspension).toContainText('Status saat ini')
  await expect(suspension).toContainText('1.183 pengguna')
  await expect(suspension.getByRole('heading', { name: 'Konfirmasi penangguhan sementara' })).toBeFocused()
  await expect(suspension).not.toContainText('Nonaktifkan')
  const hasOverflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)
  expect(hasOverflow).toBe(false)
  for (const width of [320, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await suspension.evaluate((element) => element.scrollWidth > element.clientWidth)).toBe(false)
    await page.screenshot({ path: testInfo.outputPath(`status-confirm-${width}.png`), fullPage: true })
  }
  await page.setViewportSize({ width: 320, height: 700 })
  await suspension.getByRole('button', { name: 'Simulasikan penangguhan' }).focus()
  await page.keyboard.press('Tab')
  await expect(suspension.getByRole('button', { name: 'Tutup dialog' })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await page.keyboard.press('Enter')
  await expect(suspension.getByRole('button', { name: 'Menyiapkan simulasi…' })).toBeDisabled()
  await expect(suspension.getByRole('heading', { name: 'Simulasi penangguhan selesai' })).toBeFocused()
  await expect(suspension).toContainText('Status sekolah tetap Aktif')
  await suspension.getByRole('button', { name: 'Selesai' }).click()
  await expect(trigger).toBeFocused()
  await trigger.click()
  await expect(suspension.getByRole('button', { name: 'Simulasikan penangguhan' })).toBeEnabled()
  await suspension.press('Escape')
  await expect(trigger).toBeFocused()
})

test('school reactivation and failed suspension retain the selected context', async ({ page }) => {
  await page.goto('/review/platform/schools?suspended=yogyakarta')
  await page.getByRole('button', { name: 'Tindakan SMPN 5 Yogyakarta' }).click()
  await page.getByRole('button', { name: 'Aktifkan kembali' }).click()
  const reactivation = page.getByRole('dialog', { name: 'Aktifkan kembali SMPN 5 Yogyakarta?' })
  await expect(reactivation).toContainText('Ditangguhkan')
  await reactivation.getByRole('button', { name: 'Simulasikan pengaktifan' }).click()
  await expect(reactivation).toContainText('Status sekolah tetap Ditangguhkan')
  await reactivation.press('Escape')

  await page.goto('/review/platform/schools?status=failure')
  await page.getByRole('button', { name: 'Tindakan SMPN 5 Yogyakarta' }).click()
  const trigger = page.getByRole('button', { name: 'Tangguhkan' })
  await trigger.click()
  const dialog = page.getByRole('dialog', { name: 'Tangguhkan SMPN 5 Yogyakarta?' })
  await dialog.getByRole('button', { name: 'Simulasikan penangguhan' }).click()
  await expect(dialog.getByRole('alert')).toContainText('Pilihan tetap tersimpan')
  await dialog.getByRole('button', { name: 'Coba lagi' }).click()
  await dialog.press('Escape')
  await expect(trigger).toBeFocused()
  await trigger.click()
  await expect(dialog.getByRole('button', { name: 'Simulasikan penangguhan' })).toBeEnabled()
  await expect(dialog.getByRole('alert')).toHaveCount(0)
})

test('admin handoff reviews the selected school, reflows and restores keyboard focus', async ({ page }, testInfo) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/review/platform/schools')
  await page.getByRole('button', { name: 'Tindakan SMPN 5 Yogyakarta' }).click()
  const trigger = page.getByRole('button', { name: 'Ganti admin sekolah' })
  await trigger.focus()
  await page.keyboard.press('Enter')
  const dialog = page.getByRole('dialog', { name: 'Ganti admin SMPN 5 Yogyakarta' })
  await expect(dialog).toContainText('Hendra Santoso')
  const email = dialog.getByRole('textbox', { name: 'Email admin baru' })
  await dialog.getByRole('button', { name: 'Tinjau penggantian' }).click()
  await expect(email).toBeFocused()
  await expect(email).toHaveAttribute('aria-invalid', 'true')
  await email.fill('operator.dengan.alamat.contoh.yang.panjang@example.test')
  for (const width of [320, 375, 768, 1024, 1440, 1920]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth), `page at ${width}px`).toBe(false)
    expect(await dialog.evaluate((element) => element.scrollWidth > element.clientWidth), `dialog at ${width}px`).toBe(false)
    if (width === 375 || width === 1440) await page.screenshot({ path: testInfo.outputPath(`handoff-edit-${width}.png`), fullPage: true })
  }
  await dialog.getByRole('button', { name: 'Tinjau penggantian' }).click()
  const heading = dialog.getByRole('heading', { name: 'Konfirmasi penggantian admin' })
  await expect(heading).toBeFocused()
  await page.setViewportSize({ width: 320, height: 700 })
  expect(await dialog.evaluate((element) => element.scrollWidth > element.clientWidth)).toBe(false)
  await page.screenshot({ path: testInfo.outputPath('handoff-confirm-320.png'), fullPage: true })
  await dialog.getByRole('button', { name: 'Ubah email' }).click()
  await expect(email).toHaveValue('operator.dengan.alamat.contoh.yang.panjang@example.test')
  await expect(email).toBeFocused()
  await dialog.getByRole('button', { name: 'Tinjau penggantian' }).click()
  await dialog.getByRole('button', { name: 'Simulasikan penggantian' }).click()
  await expect(dialog.getByRole('button', { name: /Menyiapkan simulasi/ })).toBeDisabled()
  await expect(dialog.getByRole('button', { name: 'Ubah email' })).toBeDisabled()
  await expect(dialog.getByRole('heading', { name: 'Simulasi penggantian selesai' })).toBeFocused()
  await dialog.press('Escape')
  await expect(trigger).toBeFocused()
  await expect(page.getByRole('table')).toContainText('Hendra Santoso')
  await trigger.click()
  await expect(email).toHaveValue('')
  await dialog.getByRole('button', { name: 'Batal' }).focus()
  await page.keyboard.press('Shift+Tab')
  await expect(email).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(dialog.getByRole('button', { name: 'Tutup dialog' })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(dialog.getByRole('button', { name: 'Tinjau penggantian' })).toBeFocused()
})

test('admin handoff failure retains the email and Escape cancels pending review', async ({ page }) => {
  await page.goto('/review/platform/schools?handoff=failure')
  await page.getByRole('button', { name: 'Tindakan SMPN 5 Yogyakarta' }).click()
  const trigger = page.getByRole('button', { name: 'Ganti admin sekolah' })
  await trigger.click()
  const dialog = page.getByRole('dialog', { name: 'Ganti admin SMPN 5 Yogyakarta' })
  const email = dialog.getByRole('textbox', { name: 'Email admin baru' })
  await email.fill('operator@example.test')
  await dialog.getByRole('button', { name: 'Tinjau penggantian' }).click()
  await dialog.getByRole('button', { name: 'Simulasikan penggantian' }).click()
  await expect(dialog.getByRole('alert')).toContainText('Simulasi belum berhasil')
  await dialog.getByRole('button', { name: 'Ubah email' }).click()
  await expect(email).toHaveValue('operator@example.test')
  await dialog.getByRole('button', { name: 'Tinjau penggantian' }).click()
  await dialog.getByRole('button', { name: 'Simulasikan penggantian' }).click()
  await dialog.press('Escape')
  await expect(trigger).toBeFocused()
  await trigger.click()
  await expect(email).toHaveValue('')
})
