// Tailwind classes for TeacherAttentionPage.tsx.
// `teacherattentionqueue-*` names carry no styles: they are hooks for the nested selectors in other entries.
const styles = {
  content: 'teacherattentionqueue-content mx-auto gap-6 max-w-340 grid [&_:is(a,_button,_input):focus-visible]:[outline:2px_solid_var(--color-primary)] [&_:is(a,_button,_input):focus-visible]:outline-offset-[3px] [&_:is(a,_button,_input):focus-visible]:[scroll-margin-block:80px]',
  header: '[&>div:first-child]:min-w-0 [&>div:first-child]:flex-[1_1_280px] py-2 gap-6 flex flex-wrap items-center [&_h1]:m-0 [&_h1]:text-[28px] [&_h1]:leading-[36px] [&_h1]:tracking-[-.03em] [&_p]:mx-0 [&_p]:mt-2 [&_p]:mb-0 [&_p]:max-w-[65ch] [&_p]:text-[14px] [&_p]:leading-[24px] [&_p]:text-text-secondary max-md:[&_h1]:text-[26px] max-md:[&_h1]:leading-[34px]',
  panel: 'px-6 pt-0 pb-8 min-w-0 bg-surface rounded-[24px] max-md:px-4 max-md:pt-0 max-md:pb-6 max-md:rounded-[20px]',
  tabs: 'gap-6 [border-bottom-style:solid] border-b border-b-role-border flex overflow-x-auto [scrollbar-width:none] [&::-webkit-scrollbar]:hidden [&_button]:px-0 [&_button]:py-3 [&_button]:gap-2 [&_button]:min-h-14 [&_button]:flex-none [&_button]:border-none [&_button]:border-0 [&_button]:border-current [&_button]:bg-transparent [&_button]:flex [&_button]:items-center [&_button]:rounded-none [&_button]:text-text-secondary [&_button]:text-[13px] [&_button]:font-medium [&_button]:[box-shadow:inset_0_-2px_0_transparent] [&_button]:[transition:color_140ms_ease-out,box-shadow_140ms_ease-out] [&_button:hover:not(:disabled)]:bg-transparent [&_button:hover:not(:disabled)]:text-ink [&_button:disabled]:opacity-55 [&_button[aria-pressed=true]]:text-primary-hover [&_button[aria-pressed=true]]:font-[650] [&_button[aria-pressed=true]]:[box-shadow:inset_0_-2px_0_var(--color-primary)] [&_button_span]:p-0 [&_button_span]:min-w-0 [&_button_span]:inline-block [&_button_span]:tabular-nums [&_button_span]:rounded-none [&_button_span]:[background:none] [&_button_span]:text-text-secondary [&_button_span]:text-[13px] [&_button_span]:leading-[20px] [&_button_span]:font-bold [&_button[aria-pressed=true]_span]:[background:none] [&_button_span[data-urgent=true]]:text-danger-text max-md:-mx-4 max-md:px-4 max-md:gap-5 motion-reduce:[&_button]:[transition:none] [&_button[aria-pressed=true]_span:where(:not(&_button_span[data-urgent=true]))]:text-primary-hover',
  toolbar: 'pt-6 pb-0 gap-3 flex flex-wrap items-center [&>div]:flex-[0_1_190px] max-md:[&>div]:flex-[1_1_135px]',
  search: 'px-3 gap-3 min-w-0 max-w-105 min-h-11 flex-[1_1_240px] border-solid border border-control-border flex items-center rounded-[12px] text-text-secondary [&_input]:px-0 [&_input]:py-2 [&_input]:w-full [&_input]:min-w-0 [&_input]:border-none [&_input]:border-0 [&_input]:border-current [&_input]:bg-transparent [&_input]:[font-style:inherit] [&_input]:text-ink [&_input]:caret-primary [&_input]:[font-variant:inherit] [&_input]:[font-weight:inherit] [&_input]:[font-stretch:inherit] [&_input]:text-[14px] [&_input]:leading-[24px] [&_input]:[font-family:inherit] [&_input::placeholder]:text-text-muted [&_input::placeholder]:opacity-100 [&_input:focus-visible]:outline-none [&_input:focus-visible]:[outline-width:medium] focus-within:[outline:2px_solid_var(--color-primary)] focus-within:outline-offset-[3px] [.teacherattentionqueue-content_&_input:focus-visible]:outline-none [.teacherattentionqueue-content_&_input:focus-visible]:[outline-width:0] max-md:max-w-none max-md:basis-full',
  reset: 'px-3 py-2 min-h-11 border-none bg-transparent text-primary-hover text-[13px] font-semibold hover:not-disabled:bg-nav-hover',
  resultCount: 'mx-0 mt-4 mb-2 tabular-nums text-text-muted text-[12px] leading-[20px]',
  group: 'teacherattentionqueue-group mt-8',
  groupHead: 'gap-y-1 gap-x-3 flex flex-wrap items-center [&_h2]:m-0 [&_h2]:text-[17px] [&_h2]:leading-[24px] [&_h2]:font-[650] [&_h2]:tracking-[-.02em] [&_p]:m-0 [&_p]:basis-full [&_p]:text-[13px] [&_p]:leading-[22px] [&_p]:text-text-secondary [.teacherattentionqueue-group[data-kind=safety]_&_h2]:text-danger-text',
  groupCount: 'tabular-nums text-text-secondary text-[15px] leading-[24px] font-bold [.teacherattentionqueue-group[data-kind=safety]_&]:text-danger-text',
  list: '-mx-3 mt-3 mb-0 p-0 list-none [&_li+li]:border-t [&_li+li]:border-t-role-border [.teacherattentionqueue-group[data-kind=safety]_&]:mx-0 [.teacherattentionqueue-group[data-kind=safety]_&]:px-2 [.teacherattentionqueue-group[data-kind=safety]_&]:py-1 [.teacherattentionqueue-group[data-kind=safety]_&]:bg-danger-bg [.teacherattentionqueue-group[data-kind=safety]_&]:rounded-[16px] [.teacherattentionqueue-group[data-kind=safety]_&_li+li]:border-[color-mix(in_srgb,var(--color-danger-text)_18%,transparent)] max-md:-mx-2 max-md:[.teacherattentionqueue-group[data-kind=safety]_&]:mx-0 max-md:[.teacherattentionqueue-group[data-kind=safety]_&]:px-1',
  row: 'teacherattentionqueue-row px-3 py-4 gap-4 grid items-center no-underline grid-cols-[40px_minmax(0,1fr)_auto] rounded-[12px] text-ink [transition:background-color_140ms_ease-out] hover:bg-paper [.teacherattentionqueue-group[data-kind=safety]_&:hover]:[background:color-mix(in_srgb,var(--color-surface)_55%,transparent)] max-md:px-2 max-md:py-4 max-md:gap-y-1 max-md:gap-x-3 max-md:items-start max-md:grid-cols-[40px_minmax(0,1fr)] motion-reduce:[transition:none]',
  lead: 'w-10 h-10 flex-none bg-paper grid items-center justify-items-center rounded-[12px] text-text-secondary data-[person=true]:[background:none] data-[person=false]:[background:none]',
  body: 'gap-0.5 min-w-0 grid',
  who: 'wrap-anywhere text-[15px] leading-[24px] font-semibold',
  summary: 'max-w-[68ch] wrap-anywhere text-[13px] leading-[22px] text-text-secondary',
  when: 'tabular-nums text-[12px] leading-[20px] text-text-muted',
  action: 'px-3 py-1.5 gap-3 min-h-9 bg-info-bg inline-flex items-center justify-between whitespace-nowrap rounded-[8px] text-primary-hover text-[12px] leading-[24px] font-[650] [transition:transform_160ms_cubic-bezier(.23,1,.32,1)] [.teacherattentionqueue-group[data-kind=safety]_&]:bg-danger-text [.teacherattentionqueue-group[data-kind=safety]_&]:text-surface [.teacherattentionqueue-row:hover_&]:underline [.teacherattentionqueue-row:hover_&]:[text-underline-offset:3px] [.teacherattentionqueue-row:active_&]:[transform:scale(.97)] max-md:mt-2 max-md:px-3.5 max-md:min-h-11 max-md:col-[2] max-md:[justify-self:start] motion-reduce:[transition:none] motion-reduce:[.teacherattentionqueue-row:active_&]:[transform:none]',
  loading: 'm-0 px-6 py-12 text-center text-text-secondary text-[14px] leading-[24px] max-md:px-2 max-md:py-8',
  emptyAction: '[.teacherattentionqueue-content_&]:px-4 [.teacherattentionqueue-content_&]:py-3 [.teacherattentionqueue-content_&]:min-h-11 [.teacherattentionqueue-content_&]:border [.teacherattentionqueue-content_&]:border-control-border [.teacherattentionqueue-content_&]:bg-surface [.teacherattentionqueue-content_&]:rounded-pill [.teacherattentionqueue-content_&]:text-primary-hover [.teacherattentionqueue-content_&]:text-[13px] [.teacherattentionqueue-content_&]:font-semibold [.teacherattentionqueue-content_&:hover:not(:disabled)]:bg-nav-hover',
} satisfies Record<string, string>

export default styles
