// Tailwind classes for TeacherClassMapPage.tsx. Layout follows "NALAR Guru.dc.html" (classmap): an 8/4 grid,
// concept rows with a stacked bar and the misconception table in the main card, counts and Nala's reading in the rail.
const styles = {
  content: 'mx-auto max-w-340 grid gap-4',
  back: 'min-h-8 inline-flex items-center gap-1 text-[13px] font-semibold text-text-muted no-underline hover:text-ink',
  header: 'gap-4 flex flex-wrap items-end justify-between [&_h1]:m-0 [&_h1]:text-[24px] [&_h1]:leading-[30px] [&_h1]:font-extrabold [&_h1]:tracking-[-.02em] [&_p]:mx-0 [&_p]:mt-0.5 [&_p]:mb-0 [&_p]:text-[14px] [&_p]:text-text-secondary',
  actions: 'gap-2 flex flex-wrap [&_button]:min-h-10 [&_button]:px-3.5 [&_button]:gap-1.5 [&_button]:whitespace-nowrap [&_button]:text-[14px] [&_button]:font-bold [&_button]:rounded-[8px] [&_button]:border-0 [&_button]:bg-surface',
  release: 'px-4 gap-2 min-h-10 bg-ink inline-flex items-center justify-center whitespace-nowrap no-underline rounded-[8px] text-white text-[14px] font-bold hover:bg-account-bubble',
  grid: 'gap-4 grid items-start grid-cols-12 max-lg:grid-cols-1',
  main: 'col-span-8 p-5 min-w-0 bg-surface rounded-2xl grid gap-4 max-lg:col-span-1',
  rail: 'col-span-4 grid gap-4 min-w-0 max-lg:col-span-1',
  card: 'p-5 min-w-0 bg-surface rounded-2xl grid gap-3 [&_h2]:m-0 [&_h2]:gap-3 [&_h2]:flex [&_h2]:items-center [&_h2]:text-[16px] [&_h2]:font-bold',
  cardHead: 'gap-4 flex flex-wrap items-center [&_h2]:m-0 [&_h2]:flex-1 [&_h2]:text-[16px] [&_h2]:font-bold',
  legend: "m-0 p-0 gap-4 flex flex-wrap list-none text-[12px] text-text-secondary [&_li]:gap-1.5 [&_li]:flex [&_li]:items-center [&_li::before]:size-2.5 [&_li::before]:bg-[#3C9A6E] [&_li::before]:content-[''] [&_li::before]:rounded-[3px] [&_li[data-kind=developing]::before]:bg-accent [&_li[data-kind=unseen]::before]:bg-surface-muted",
  concepts: 'm-0 p-0 list-none grid gap-1 [&_li]:p-3 [&_li]:gap-4 [&_li]:grid [&_li]:items-center [&_li]:grid-cols-[200px_minmax(0,1fr)_auto] [&_li]:rounded-xl [&_li:hover]:bg-paper [&_strong]:text-[14px] [&_small]:text-[13px] [&_small]:text-text-secondary [&_small]:text-right max-md:[&_li]:grid-cols-1 max-md:[&_small]:text-left',
  bar: 'h-3 gap-0.5 flex overflow-hidden rounded-pill [&_span]:min-w-0 [&_span:nth-child(1)]:bg-[#3C9A6E] [&_span:nth-child(2)]:bg-accent [&_span:nth-child(3)]:bg-surface-muted',
  system: 'm-0 px-3 py-2 bg-paper rounded-[10px] text-[12px] text-text-secondary',
  mapRegion: 'relative overflow-x-auto rounded-xl',
  map: 'h-60 min-w-130 relative rounded-xl [background:#FBFAF7_radial-gradient(#E4E0D7_1px,transparent_1px)_0_0_/_16px_16px] [&_svg]:inset-0 [&_svg]:w-full [&_svg]:h-full [&_svg]:absolute [&_path]:[fill:none] [&_path]:stroke-text-muted [&_path]:[stroke-width:1.25] [&_path]:opacity-50 [&_path]:[vector-effect:non-scaling-stroke] [&_ul]:m-0 [&_ul]:p-0 [&_ul]:list-none [&_li]:px-3 [&_li]:h-7.5 [&_li]:flex [&_li]:items-center [&_li]:whitespace-nowrap [&_li]:bg-surface [&_li]:absolute [&_li]:[transform:translate(-50%,-50%)] [&_li]:rounded-[8px] [&_li]:text-[13px] [&_li]:font-bold [&_li]:shadow-[0_1px_2px_rgb(21_33_59/6%)]',
  table: 'pt-4 border-t border-paper grid gap-2 [&_h3]:m-0 [&_h3]:gap-2 [&_h3]:flex [&_h3]:items-center [&_h3]:text-[13px] [&_h3]:font-bold [&_h3]:text-text-secondary [&_h3_span]:px-2 [&_h3_span]:rounded-pill [&_h3_span]:bg-paper [&_h3_span]:text-[12px] [&_p]:m-0 [&_p]:text-[14px] [&_p]:text-text-secondary',
  tableRegion: 'relative overflow-x-auto [&_table]:w-full [&_table]:min-w-160 [&_table]:border-collapse [&_table]:text-[13px] [&_caption]:sr-only [&_thead_th]:px-2 [&_thead_th]:h-10 [&_thead_th]:text-start [&_thead_th]:text-[12px] [&_thead_th]:font-bold [&_thead_th]:text-text-muted [&_tbody_th]:px-2 [&_tbody_th]:py-3 [&_tbody_th]:text-start [&_tbody_th]:text-[14px] [&_tbody_th]:font-bold [&_tbody_th]:align-top [&_td]:px-2 [&_td]:py-3 [&_td]:align-top [&_th:nth-child(1)]:w-[30%] [&_th:nth-child(3)]:w-44 [&_th:nth-child(4)]:w-28 [&_td]:text-text-secondary [&_td>strong]:text-[14px] [&_td>strong]:font-extrabold [&_td>strong]:text-ink [&_tbody_tr]:border-t [&_tbody_tr]:border-paper',
  chips: 'mt-2 mb-0 p-0 list-none flex flex-wrap gap-1.5 [&_a]:h-7 [&_a]:px-2.5 [&_a]:flex [&_a]:items-center [&_a]:rounded-pill [&_a]:bg-paper [&_a]:text-[13px] [&_a]:font-semibold [&_a]:text-ink [&_a]:no-underline [&_a:hover]:bg-info-bg',
  progress: 'gap-2 flex items-center whitespace-nowrap text-[13px] font-bold text-success-strong [&>span]:h-1.5 [&>span]:w-16 [&>span]:flex-none [&>span]:bg-[#F3F1EC] [&>span]:overflow-hidden [&>span]:rounded-pill [&_i]:h-full [&_i]:bg-[#3C9A6E] [&_i]:block',
  kpis: 'm-0 gap-3 grid grid-cols-2 [&>div]:px-4 [&>div]:py-3 [&>div]:rounded-xl [&>div]:bg-surface [&_dt]:text-[13px] [&_dt]:text-text-secondary [&_dd]:m-0 [&_dd]:text-[22px] [&_dd]:font-extrabold [&_dd]:tracking-[-.02em] [&_dd]:tabular-nums',
  story: 'm-0 text-[14px] leading-[1.6] text-account-bubble [text-wrap:pretty]',
  footnote: 'm-0 pt-3 border-t border-paper text-[12px] leading-[1.5] text-text-muted',
  suggestions: 'm-0 p-0 grid gap-2 list-none [&_li]:text-[14px] [&_li]:leading-[1.55] [&_li]:text-text-secondary [&_li+li]:pt-2 [&_li+li]:border-t [&_li+li]:border-paper',
} satisfies Record<string, string>

export default styles
