// Tailwind classes for TeacherReleasePage.tsx.
// `teacherrelease-*` names carry no styles: they are hooks for the nested selectors in other entries.
const styles = {
  content: 'max-w-340',
  back: 'gap-1 min-h-11 inline-flex items-center no-underline text-[13px] font-semibold text-text-secondary hover:text-primary',
  header: 'gap-4 flex flex-wrap items-end justify-between [&_h1]:m-0 [&_h1]:text-[22px] [&_h1]:leading-[30px] [&_h1]:tracking-[-.015em] [&_p]:mx-0 [&_p]:mt-0.5 [&_p]:mb-0 [&_p]:text-[13px] [&_p]:text-text-muted [&_button]:gap-1.5 [&_button]:whitespace-nowrap [&_button]:text-[13px] [&_button]:rounded-[8px] [&_button:disabled]:border-success-bg [&_button:disabled]:bg-success-bg [&_button:disabled]:text-success-strong [&_button:disabled]:opacity-100',
  note: 'mx-0 mt-2 mb-0 max-w-[72ch] text-[13px] leading-[20px] text-text-secondary',
  banner: 'mx-0 mt-4 mb-0 px-3 py-2.5 gap-2 bg-nav-hover flex items-center [--nala-ring:var(--color-nav-hover)] rounded-[8px] text-[12px] leading-[18px] data-[released=true]:bg-success-bg data-[released=true]:[--nala-ring:var(--color-success-bg)] data-[released=true]:text-success-strong',
  grid: 'mt-4 gap-4 grid items-start grid-cols-[minmax(0,2fr)_minmax(0,1fr)] [@media(max-width:900px)]:grid-cols-[minmax(0,1fr)]',
  table: 'min-w-0 border border-role-border bg-surface overflow-hidden rounded-[14px] [&_h2]:m-0 [&_h2]:px-4 [&_h2]:py-3 [&_h2]:gap-2 [&_h2]:border-b [&_h2]:border-b-role-border [&_h2]:flex [&_h2]:items-center [&_h2]:text-[14px] [&_h2]:leading-[22px] [&_h2_span]:px-[7px] [&_h2_span]:py-px [&_h2_span]:border [&_h2_span]:border-role-border [&_h2_span]:rounded-[999px] [&_h2_span]:text-[11px] [&_h2_span]:font-semibold',
  preview: 'teacherrelease-preview p-4 top-18 min-w-0 border border-role-border bg-surface sticky rounded-[14px] [&_h2]:m-0 [&_h2]:text-[11px] [&_h2]:font-semibold [&_h2]:tracking-[.06em] [&_h2]:text-text-muted [&_p]:mx-0 [&_p]:mt-3 [&_p]:mb-0 [&_p]:text-[13px] [&_p]:leading-[21px] [@media(max-width:900px)]:static',
  region: 'overflow-x-auto [&_table]:w-full [&_table]:min-w-115 [&_table]:border-collapse [&_table]:text-[13px] [&_caption]:w-px [&_caption]:h-px [&_caption]:overflow-hidden [&_caption]:absolute [&_caption]:[clip-path:inset(50%)] [&_thead_th]:px-4 [&_thead_th]:py-2.5 [&_thead_th]:bg-canvas [&_thead_th]:text-start [&_thead_th]:text-[11px] [&_thead_th]:font-semibold [&_thead_th]:tracking-[.06em] [&_thead_th]:text-text-muted [&_tbody_tr]:[border-top-style:solid] [&_tbody_tr]:border-t [&_tbody_tr]:border-t-surface-muted [&_tbody_tr[data-selected=true]]:bg-nav-hover [&_tbody_tr[data-selected=true]]:[box-shadow:inset_2px_0_0_var(--color-primary)] [&_tbody_th]:px-4 [&_tbody_th]:py-0 [&_tbody_th]:text-start [&_tbody_th]:font-semibold [&_tbody_th_button]:p-0 [&_tbody_th_button]:min-w-11 [&_tbody_th_button]:border-none [&_tbody_th_button]:border-0 [&_tbody_th_button]:border-current [&_tbody_th_button]:text-start [&_tbody_th_button]:[font-style:inherit] [&_tbody_th_button]:[background:none] [&_tbody_th_button]:text-ink [&_tbody_th_button]:[font-variant:inherit] [&_tbody_th_button]:font-semibold [&_tbody_th_button]:[font-stretch:inherit] [&_tbody_th_button]:[font-size:inherit] [&_tbody_th_button]:[line-height:inherit] [&_tbody_th_button]:[font-family:inherit] [&_tbody_th:not(:has(button))]:py-3 [&_tbody_th:not(:has(button))]:text-text-secondary [&_td]:px-4 [&_td]:py-3 [&_td]:text-text-secondary [&_td_span]:px-2 [&_td_span]:py-0.5 [&_td_span]:bg-success-bg [&_td_span]:whitespace-nowrap [&_td_span]:rounded-[6px] [&_td_span]:text-[11px] [&_td_span]:font-bold [&_td_span]:text-success-strong [&_td_span[data-ready=false]]:bg-paper [&_td_span[data-ready=false]]:text-text-muted',
  who: 'mt-3 gap-2.5 flex items-center [&>span]:w-9 [&>span]:h-9 [&>span]:flex-none [&>span]:bg-warning-bg [&>span]:grid [&>span]:items-center [&>span]:justify-items-center [&>span]:rounded-[50%] [&>span]:text-warning-text [&>span]:font-bold [&_strong]:block [&_strong]:text-[14px] [&_small]:text-[12px] [&_small]:text-text-muted',
  home: '[.teacherrelease-preview_&]:px-3 [.teacherrelease-preview_&]:py-2.5 [.teacherrelease-preview_&]:bg-warning-bg [.teacherrelease-preview_&]:rounded-[8px] [.teacherrelease-preview_&]:text-[12px] [.teacherrelease-preview_&]:leading-[18px] [.teacherrelease-preview_&_strong]:text-warning-text',
  lock: '[.teacherrelease-preview_&]:gap-1.5 [.teacherrelease-preview_&]:flex [.teacherrelease-preview_&]:items-center [.teacherrelease-preview_&]:text-[11px] [.teacherrelease-preview_&]:leading-[16px] [.teacherrelease-preview_&]:text-text-muted',
} satisfies Record<string, string>

export default styles
