// Tailwind classes for TeacherKbListPage.tsx.
// `teacherkblibrary-*` names carry no styles: they are hooks for the nested selectors in other entries.
const styles = {
  content: 'teacherkblibrary-content mx-auto gap-6 max-w-340 grid',
  header: 'teacherkblibrary-header [&>div:first-child]:min-w-0 [&>div:first-child]:flex-[1_1_280px] py-2 gap-6 flex flex-wrap items-center justify-between [&_h1]:m-0 [&_h1]:text-[28px] [&_h1]:leading-[36px] [&_h1]:tracking-[-.03em] [&_p]:mx-0 [&_p]:mt-2 [&_p]:mb-0 [&_p]:max-w-[65ch] [&_p]:text-[14px] [&_p]:leading-[24px] [&_p]:text-text-secondary [@media(max-width:600px)]:gap-4 [@media(max-width:600px)]:[&_h1]:text-[26px] [@media(max-width:600px)]:[&_h1]:leading-[34px]',
  upload: '[.teacherkblibrary-header_&]:px-6 [.teacherkblibrary-header_&]:min-h-12 [.teacherkblibrary-header_&]:rounded-pill [.teacherkblibrary-header_&]:text-[14px]',
  library: 'p-6 min-w-0 bg-surface rounded-[24px] [@media(max-width:600px)]:px-4 [@media(max-width:600px)]:py-5 [@media(max-width:600px)]:rounded-[20px]',
  libraryHead: 'gap-2 flex flex-wrap items-center justify-between [&_h2]:m-0 [&_h2]:text-[20px] [&_h2]:leading-[28px] [&_h2]:tracking-[-.02em] [&>span]:tabular-nums [&>span]:text-[12px] [&>span]:text-text-muted',
  filters: 'mt-6 gap-y-0 gap-x-6 [border-bottom-style:solid] border-b border-b-role-border flex flex-wrap [&_button]:px-0 [&_button]:py-3 [&_button]:gap-2 [&_button]:min-h-12 [&_button]:border-none [&_button]:border-0 [&_button]:border-current [&_button]:bg-transparent [&_button]:flex [&_button]:items-center [&_button]:rounded-none [&_button]:text-text-secondary [&_button]:text-[13px] [&_button]:font-medium [&_button:hover:not(:disabled)]:bg-transparent [&_button:hover:not(:disabled)]:text-ink [&_button[aria-pressed=true]]:text-primary-hover [&_button[aria-pressed=true]]:[box-shadow:inset_0_-2px_var(--color-primary)] [&_button[aria-pressed=true]]:font-semibold [&_button_span]:p-0 [&_button_span]:min-w-0 [&_button_span]:inline-block [&_button_span]:tabular-nums [&_button_span]:rounded-none [&_button_span]:[background:none] [&_button_span]:text-text-secondary [&_button_span]:text-[13px] [&_button_span]:leading-[20px] [&_button_span]:font-bold [&_button[aria-pressed=true]_span]:[background:none] [&_button[aria-pressed=true]_span]:text-primary-hover [@media(max-width:600px)]:gap-y-0 [@media(max-width:600px)]:gap-x-5 [@media(max-width:600px)]:[&_button]:text-[12px]',
  toolbar: 'mt-6 gap-3 flex flex-wrap items-center [&>div]:flex-[0_1_164px] [@media(max-width:600px)]:[&>div]:flex-[1_1_130px]',
  search: 'px-3 gap-3 min-w-0 max-w-105 min-h-11 flex-[1_1_240px] border-solid border border-control-border flex items-center rounded-[12px] text-text-secondary [&_input]:px-0 [&_input]:py-2 [&_input]:w-full [&_input]:min-w-0 [&_input]:border-none [&_input]:border-0 [&_input]:border-current [&_input]:bg-transparent [&_input]:[font-style:inherit] [&_input]:text-ink [&_input]:[font-variant:inherit] [&_input]:[font-weight:inherit] [&_input]:[font-stretch:inherit] [&_input]:text-[14px] [&_input]:leading-[24px] [&_input]:[font-family:inherit] [&_input::placeholder]:text-text-muted [&_input::placeholder]:opacity-100 [&_input:focus-visible]:outline-none focus-within:[outline:2px_solid_var(--color-primary)] focus-within:outline-offset-[3px] [@media(max-width:600px)]:max-w-none [@media(max-width:600px)]:basis-full',
  reset: 'px-3 py-2 min-h-11 border-none bg-transparent text-primary-hover text-[13px] font-semibold hover:not-disabled:bg-nav-hover',
  resultCount: 'mx-0 mt-4 mb-6 tabular-nums text-[12px] leading-[20px] text-text-muted',
  columns: 'py-3 gap-6 border-t border-b border-t-role-border border-b-role-border grid items-center grid-cols-[minmax(0,1.4fr)_minmax(230px,1fr)_150px] text-[12px] text-text-secondary [@media(max-width:1050px)]:hidden',
  row: 'teacherkblibrary-row py-6 gap-6 grid items-center grid-cols-[minmax(0,1.4fr)_minmax(230px,1fr)_150px] [.teacherkblibrary-row+&]:border-t [.teacherkblibrary-row+&]:border-t-role-border [@media(max-width:1050px)]:gap-y-3 [@media(max-width:1050px)]:gap-x-6 [@media(max-width:1050px)]:grid-cols-[minmax(0,1fr)_150px] [@media(max-width:600px)]:grid-cols-[minmax(0,1fr)]',
  list: 'm-0 p-0 list-none',
  identity: 'gap-4 min-w-0 flex items-start [&>div]:min-w-0 [&_h3]:m-0 [&_h3]:wrap-anywhere [&_h3]:text-[15px] [&_h3]:leading-[24px] [&_h3]:font-semibold [&_h3_a]:no-underline [&_h3_a]:text-ink [&_h3_a:hover]:underline [&_h3_a:hover]:[text-underline-offset:4px] [&_p]:mx-0 [&_p]:mt-1 [&_p]:mb-0 [&_p]:wrap-anywhere [&_p]:text-[12px] [&_p]:leading-[20px] [&_p]:text-text-secondary [&_p:last-child]:text-text-muted',
  fileIcon: 'w-11 h-11 flex-none grid items-center justify-items-center',
  review: 'gap-2 min-w-0 grid [&_dl]:m-0 [&_dl]:gap-3 [&_dl]:flex [&_dl]:flex-wrap [&_dl_div]:gap-1 [&_dl_div]:flex [&_dl_div]:flex-col-reverse [&_dt]:text-[11px] [&_dt]:leading-[18px] [&_dt]:text-text-muted [&_dd]:m-0 [&_dd]:tabular-nums [&_dd]:text-[16px] [&_dd]:leading-[24px] [&_dd]:font-semibold [@media(max-width:1050px)]:pl-15 [@media(max-width:1050px)]:row-[2] [@media(max-width:600px)]:row-[auto]',
  status: 'text-[12px] leading-[20px] font-semibold text-text-secondary data-[status=review]:text-warning-text data-[status=approved]:text-success-text',
  action: 'gap-3 min-h-11 inline-flex items-center justify-between no-underline rounded-[8px] text-primary-hover text-[13px] leading-[20px] font-semibold hover:underline hover:[text-underline-offset:4px] [@media(max-width:1050px)]:col-[2] [@media(max-width:1050px)]:row-[1_/_3] [@media(max-width:600px)]:ml-15 [@media(max-width:600px)]:[justify-content:start] [@media(max-width:600px)]:col-[auto] [@media(max-width:600px)]:row-[auto]',
  note: 'mx-0 mt-2 mb-0 pt-4 gap-2 border-t border-t-role-border flex items-center text-[12px] leading-[20px] text-text-secondary',
  loading: 'm-0 px-6 py-12 text-center text-text-secondary text-[14px] leading-[24px] [@media(max-width:600px)]:px-2 [@media(max-width:600px)]:py-8',
  emptyAction: '[.teacherkblibrary-content_&]:px-4 [.teacherkblibrary-content_&]:py-3 [.teacherkblibrary-content_&]:min-h-11 [.teacherkblibrary-content_&]:rounded-pill [.teacherkblibrary-content_&]:text-[13px] [button&]:border [button&]:border-control-border [button&]:bg-surface [button&]:text-primary-hover [button&]:font-semibold [button&:hover:not(:disabled)]:bg-nav-hover',
} satisfies Record<string, string>

export default styles
