// Tailwind classes for TeacherReportPage.tsx, TeacherStudentHistoryPage.tsx.
// Layout follows "NALAR Guru.dc.html" (report): a sticky 4-column rail (scores, flags, concepts) beside an 8-column dialog card.
// `teacherreport-*` names carry no styles: they are hooks for the nested selectors in other entries.
const styles = {
  content: 'mx-auto max-w-340 grid gap-4',
  back: 'gap-1 min-h-8 inline-flex items-center no-underline text-[13px] font-semibold text-text-muted hover:text-ink',
  header: 'gap-4 flex flex-wrap items-center justify-between [&_h1_a]:text-inherit [&_h1_a]:no-underline [&_h1_a:hover]:text-primary',
  who: 'gap-3 min-w-0 flex items-center [&_h1]:m-0 [&_h1]:wrap-anywhere [&_h1]:text-[24px] [&_h1]:leading-[30px] [&_h1]:font-extrabold [&_h1]:tracking-[-.02em] [&_p]:mx-0 [&_p]:mt-0.5 [&_p]:mb-0 [&_p]:text-[14px] [&_p]:text-text-secondary',
  avatar: 'w-12 h-12 flex-none grid items-center justify-items-center',
  headerActions: 'gap-2 flex flex-wrap items-start justify-end [&_button]:min-h-10 [&_button]:px-3.5 [&_button]:gap-1.5 [&_button]:whitespace-nowrap [&_button]:text-[14px] [&_button]:font-bold [&_button]:rounded-[8px] [&_button]:border-0 [&_button]:bg-surface',
  note: 'm-0 max-w-[72ch] text-[13px] leading-[20px] text-text-muted',
  scenario: 'gap-y-2 gap-x-3 flex flex-wrap items-center text-[13px] font-semibold [&_select]:px-2.5 [&_select]:min-h-10 [&_select]:border-0 [&_select]:bg-surface [&_select]:rounded-[8px] [&_select]:text-ink',
  retry: 'mt-2 flex flex-wrap gap-2',
  thinking: 'm-0 text-[14px] font-semibold text-primary',
  grid: 'gap-4 grid items-start grid-cols-12 max-lg:grid-cols-1',
  column: 'col-span-4 gap-4 min-w-0 flex flex-col lg:sticky lg:top-4 max-lg:col-span-1',
  card: 'p-5 min-w-0 bg-surface rounded-2xl grid gap-1 [&_h2]:m-0 [&_h2]:text-[16px] [&_h2]:font-bold',
  cardHead: 'mb-2 gap-3 flex items-baseline [&_h2]:m-0 [&_h2]:flex-1 [&_h2]:text-[16px] [&_h2]:font-bold [&>span]:text-[12px] [&>span]:text-text-muted',
  scores: 'teacherreport-scores m-0 grid [&>div]:py-3 [&>div]:border-t [&>div]:border-paper [&_dt]:text-[14px] [&_dt]:font-bold [&_dd]:m-0 [&>div]:grid [&>div]:grid-cols-[minmax(0,1fr)_auto] [&>div]:gap-x-3 [&>div]:gap-y-2 [&_dd]:contents',
  value: 'row-start-1 col-start-2 justify-self-end gap-1.5 flex items-baseline [&_strong]:text-[20px] [&_strong]:font-extrabold [&_s]:text-[12px] [&_s]:text-text-muted',
  bar: 'col-start-1 col-span-2 row-start-2 gap-1 flex [&_span]:h-1.5 [&_span]:flex-1 [&_span]:bg-[#F3F1EC] [&_span]:rounded-pill [&_span[data-on=true]]:bg-primary',
  scoreFoot: 'col-start-1 col-span-2 row-start-3 gap-x-3 gap-y-1 flex flex-wrap items-baseline text-[13px] [&_button]:p-0 [&_button]:min-h-0 [&_button]:border-0 [&_button]:bg-transparent [&_button]:text-primary [&_button]:text-[13px] [&_button]:font-bold [&_button:hover]:text-primary-hover [&_button[aria-pressed=true]]:underline [&_button[aria-pressed=true]]:underline-offset-4',
  level: 'flex-1 min-w-0 text-text-muted [.teacherreport-scores>div[data-status=overridden]_&]:text-primary [.teacherreport-scores>div[data-status=overridden]_&]:font-semibold [.teacherreport-scores>div[data-status=no-evidence]_&]:text-warning-text [.teacherreport-scores>div[data-status=no-evidence]_&]:font-semibold',
  changes: 'mt-2 mb-0 p-3 gap-1 grid list-none rounded-xl bg-paper text-[13px] leading-[20px] text-text-secondary [&_b]:text-ink',
  flag: 'p-5 min-w-0 bg-danger-bg rounded-2xl grid gap-2 [&>p:first-child]:m-0 [&>p:first-child]:gap-1.5 [&>p:first-child]:flex [&>p:first-child]:items-center [&>p:first-child]:text-[12px] [&>p:first-child]:font-bold [&>p:first-child]:text-danger-text [&_h2]:m-0 [&_h2]:text-[16px] [&_h2]:font-bold',
  hint: 'm-0 text-[13px] text-danger-hover',
  evidence: 'gap-1 grid [&_p]:m-0 [&_p]:text-[14px] [&_p]:leading-[21px] [&_p]:text-ink [&_p:first-child]:text-[13px] [&_p:first-child]:text-text-secondary',
  flagActions: 'gap-2 flex flex-wrap [&_button]:min-h-9 [&_button]:text-[13px] [&_button]:font-bold [&_button]:rounded-[8px] [&_button]:border-0 [&_button]:bg-surface',
  decision: 'm-0 text-[13px] text-text-secondary',
  muted: 'm-0 text-[13px] leading-[20px] text-text-muted',
  concepts: 'mt-1 mb-0 p-0 grid gap-2 list-none [&_li]:p-3 [&_li]:gap-3 [&_li]:flex [&_li]:items-start [&_li]:justify-between [&_li]:rounded-xl [&_li]:bg-paper [&_li>span]:grid [&_li>span]:gap-0.5 [&_b]:text-[14px] [&_small]:text-[13px] [&_small]:text-text-secondary [&_em]:not-italic [&_em]:whitespace-nowrap [&_em]:text-[12px] [&_em]:font-bold [&_em]:text-text-secondary [&_li[data-result=mastered]]:bg-success-bg [&_li[data-result=mastered]_em]:text-success-strong [&_li[data-result=developing]]:bg-warning-bg [&_li[data-result=developing]_em]:text-warning-text [&_li[data-result=misconception]]:bg-danger-bg [&_li[data-result=misconception]_em]:text-danger-text',
  panel: 'col-span-8 p-6 min-w-0 bg-surface rounded-2xl grid gap-5 content-start max-lg:col-span-1 max-md:p-4',
  turns: 'm-0 p-0 grid gap-6 list-none [&>li]:grid [&>li]:grid-cols-[40px_minmax(0,1fr)] [&>li]:gap-4 [&>li]:-mx-3 [&>li]:p-3 [&>li]:rounded-xl [&>li]:[transition:background-color_.4s] [&>li[data-selected=true]]:bg-info-bg/50 motion-reduce:[&>li]:[transition:none] [&>li>div]:grid [&>li>div]:gap-2.5 [&>li>div]:min-w-0',
  turnNumber: 'size-8 grid place-items-center rounded-pill bg-paper text-[13px] font-extrabold',
  turnHead: 'gap-2 flex flex-wrap items-center [&_b]:text-[12px] [&_b]:text-text-muted [&_span]:px-2.5 [&_span]:py-[3px] [&_span]:bg-info-bg [&_span]:rounded-pill [&_span]:text-primary [&_span]:text-[12px] [&_span]:font-bold [&_small]:text-[13px] [&_small]:text-danger-text',
  question: 'm-0 text-[15px] leading-[1.5] font-semibold',
  answer: 'm-0 px-4 py-3.5 bg-paper wrap-anywhere rounded-xl font-reading text-[16px] leading-[1.6] [&_mark]:px-0.5 [&_mark]:bg-warning-bg [&_mark]:rounded-[4px] [&_mark]:text-ink',
  meta: 'm-0 text-[12px] text-text-muted',
  activity: 'mt-2 mb-0 p-0 list-none text-[13px] [&_li]:py-2.5 [&_li]:gap-3 [&_li]:border-b [&_li]:border-paper [&_li]:flex [&_b]:min-w-21 [&_b]:text-[12px] [&_b]:text-text-muted',
  attempt: '[&_p]:mx-0 [&_p]:mt-2 [&_p]:mb-0 [&_p]:text-[14px]',
  hidden: 'sr-only',
} satisfies Record<string, string>

export default styles
