// Tailwind classes for LiveTeacherRun.tsx.
// `teachermonitor-*` names carry no styles: they are hooks for the nested selectors in other entries.
const styles = {
  content: 'mx-auto max-w-340',
  back: 'min-h-8 inline-flex items-center gap-1 text-[13px] font-semibold text-text-muted no-underline hover:text-ink',
  safety: 'p-3 gap-2 grid rounded-xl bg-danger-bg text-[13px] [&_strong]:text-[14px] [&_strong]:font-bold [&_strong]:text-ink [&>span]:leading-[1.45] [&>span]:text-[#7A2335] [&_a]:font-bold [&_a]:text-[#A3253F] [&_b]:font-bold [&_b]:text-ink',
  flagAlert: 'mb-4 p-3 gap-2 flex flex-wrap items-center rounded-xl bg-warning-bg text-warning-text text-[13px] [&_strong]:text-[14px] [&_strong]:font-bold [&_strong]:text-ink [&>span]:leading-[1.45] [&>span]:text-ink [&_b]:font-bold',
  safetyAction: 'px-3 min-h-8 bg-[#A3253F] whitespace-nowrap rounded-[8px] text-[13px] font-bold hover:not-disabled:bg-danger-hover max-md:min-h-11',
  header: 'px-5 py-4 gap-x-6 gap-y-3 flex flex-wrap items-center rounded-2xl bg-surface',
  title: 'gap-2 flex flex-wrap items-center [&_h1]:m-0 [&_h1]:wrap-anywhere [&_h1]:text-[24px] [&_h1]:leading-[30px] [&_h1]:font-extrabold [&_h1]:tracking-[-.02em]',
  badge: 'teachermonitor-badge px-2.5 py-1 gap-1.5 bg-success-bg inline-flex items-center rounded-pill text-success-strong text-[12px] font-bold data-[closed=true]:bg-surface data-[closed=true]:text-text-secondary',
  dot: '[.teachermonitor-badge_&]:size-2 [.teachermonitor-badge_&]:bg-[#3C9A6E] [.teachermonitor-badge_&]:rounded-pill [.teachermonitor-badge[data-closed=true]_&]:bg-current',
  actions: 'ms-auto flex flex-wrap gap-2 [&_button]:min-h-10 [&_button]:gap-2 [&_button]:px-3.5 [&_button]:text-[14px] [&_button]:font-bold [&_button]:rounded-[8px] max-md:ms-0 max-md:[&_button]:min-h-11',
  code: 'px-3.5 gap-2 min-h-10 max-md:min-h-11 bg-paper inline-flex items-center whitespace-nowrap no-underline rounded-[8px] text-ink text-[14px] font-bold hover:bg-info-bg',
  close: 'gap-2 bg-ink whitespace-nowrap text-[14px] rounded-[8px] hover:not-disabled:bg-account-bubble',
  note: 'mx-0 mt-2 mb-0 max-w-[72ch] text-[13px] leading-[20px] text-text-secondary',
  // Shown only when the link drops; while connected the status text stays for screen readers.
  connection: 'data-[connection=ok]:sr-only mt-3 px-3 py-2 gap-y-2 gap-x-4 bg-info-bg flex flex-wrap items-center justify-between rounded-[8px] text-primary-hover text-[13px] data-[connection=stale]:bg-warning-bg data-[connection=stale]:text-warning-text data-[connection=offline]:bg-danger-bg data-[connection=offline]:text-danger-text [&_label]:gap-2 [&_label]:flex [&_label]:items-center [&_label]:font-semibold [&_select]:px-2 [&_select]:py-1.5 [&_select]:min-h-11 [&_select]:border [&_select]:border-control-border [&_select]:bg-surface [&_select]:[font-style:inherit] [&_select]:rounded-[8px] [&_select]:[font-variant:inherit] [&_select]:font-normal [&_select]:[font-stretch:inherit] [&_select]:[font-size:inherit] [&_select]:[line-height:inherit] [&_select]:[font-family:inherit] [&_select]:text-ink',
  tallies: 'mt-4 grid grid-cols-2 gap-3 md:grid-cols-4 [&_button]:flex [&_button]:w-full [&_button]:min-h-11 [&_button]:items-center [&_button]:gap-3 [&_button]:rounded-xl [&_button]:border-0 [&_button]:bg-surface [&_button]:px-4 [&_button]:py-3 [&_button]:text-start [&_button]:text-ink [&_button:hover:not(:disabled)]:bg-info-bg [&_button[aria-pressed=true]]:bg-info-bg [&_button>span]:flex [&_button>span]:flex-1 [&_button>span]:items-center [&_button>span]:gap-3 [&_button>span]:text-[13px] [&_button>span]:font-medium [&_button>span]:text-text-secondary [&_i]:size-2.5 [&_i]:rounded-pill [&_i]:bg-control-border [&_i[data-group=running]]:bg-primary [&_i[data-group=done]]:bg-[#3C9A6E] [&_i[data-group=flagged]]:bg-[#D9485F] [&_strong]:text-[22px] [&_strong]:font-extrabold [&_strong]:tracking-[-.02em] [&_strong]:tabular-nums',
  roster: 'teachermonitor-roster min-w-0 p-5 bg-surface rounded-2xl grid content-start gap-4 lg:col-span-9',
  grid: '[.teachermonitor-roster[data-stale=true]_&]:opacity-72 m-0 p-0 gap-2 grid list-none grid-cols-4 max-xl:grid-cols-3 max-md:grid-cols-2 max-sm:grid-cols-1',
  rosterHead: 'gap-2 flex items-baseline justify-between [&_h2]:m-0 [&_h2]:text-[16px] [&_h2]:font-bold [&_small]:ml-2 [&_small]:text-[12px] [&_small]:font-normal [&_small]:text-text-muted [&_button]:gap-1.5 [&_button]:text-[13px] [&_button]:font-bold [&_button]:rounded-[8px]',
  empty: 'm-0 py-6 text-[14px] text-text-secondary',
  student: 'teachermonitor-student px-3 py-2.5 gap-1.5 w-full border-0 bg-paper flex flex-col text-start rounded-xl text-ink font-normal data-[status=running]:bg-info-bg data-[status=done]:bg-success-bg data-[status=paused]:bg-danger-bg data-[flagged=true]:bg-warning-bg/25 data-[flagged=true]:[box-shadow:inset_0_0_0_1.5px_color-mix(in_srgb,var(--color-warning-text)_40%,transparent)] [&_svg]:text-text-muted data-[status=running]:[&_svg]:text-primary data-[status=done]:[&_svg]:text-success-strong data-[status=paused]:[&_svg]:text-danger-text [&_button]:min-h-0 [&_button]:self-start [&_button]:border-0 [&_button]:bg-transparent [&_button]:p-0 [&_button]:text-[12px] [&_button]:font-bold [&_button]:text-text-secondary [&_button:hover:not(:disabled)]:bg-transparent [&_button:hover:not(:disabled)]:text-danger-text [&_button:hover:not(:disabled)]:underline',
  studentTop: 'gap-2 flex items-center justify-between',
  name: 'min-w-0 overflow-hidden whitespace-nowrap text-[13px] font-bold text-ink no-underline [text-overflow:ellipsis] hover:underline',
  dots: 'gap-[3px] flex [&_span]:h-1 [&_span]:flex-1 [&_span]:bg-surface [&_span]:rounded-pill [&_span[data-on=true]]:bg-primary [.teachermonitor-student[data-status=done]_&_span[data-on=true]]:bg-[#3C9A6E] [.teachermonitor-student[data-status=paused]_&_span[data-on=true]]:bg-danger-text',
  status: 'text-[11px] font-bold text-text-secondary [.teachermonitor-student[data-status=running]_&]:text-primary [.teachermonitor-student[data-status=done]_&]:text-success-strong [.teachermonitor-student[data-status=paused]_&]:text-danger-text',
  detail: 'teachermonitor-detail mt-4 p-5 bg-surface rounded-2xl [box-shadow:inset_0_0_0_2px_var(--color-primary)] [&_h2]:m-0 [&_h2]:text-[16px] [&_h2]:font-bold [&_p]:mx-0 [&_p]:mt-1 [&_p]:mb-0 [&_p]:text-[14px] [&_p]:text-text-secondary [&_button]:mt-3 [&_button]:text-[13px] [&_button]:font-bold [&_button]:rounded-[8px]',
  hint: '[.teachermonitor-detail_&]:px-3 [.teachermonitor-detail_&]:py-2 [.teachermonitor-detail_&]:bg-paper [.teachermonitor-detail_&]:rounded-[10px] [.teachermonitor-detail_&]:text-ink',
  report: 'mt-3 px-4 min-h-10 bg-paper inline-flex items-center justify-center no-underline rounded-[8px] text-ink text-[14px] font-bold hover:bg-info-bg',
  hidden: 'm-0 w-px h-px overflow-hidden absolute [clip-path:inset(50%)]',
  facts: 'm-0 flex flex-wrap gap-x-6 gap-y-2 [&_dt]:text-[12px] [&_dt]:text-text-muted [&_dd]:m-0 [&_dd]:text-[15px] [&_dd]:font-bold [&_dd]:tabular-nums [&_dd[data-code]]:font-extrabold [&_dd[data-code]]:tracking-[.12em]',
  split: 'mt-4 grid items-start gap-4 lg:grid-cols-12',
  events: 'grid min-w-0 content-start gap-3 rounded-2xl bg-surface p-5 lg:col-span-3 [&_h2]:m-0 [&_h2]:text-[16px] [&_h2]:font-bold [&_ul]:m-0 [&_ul]:grid [&_ul]:list-none [&_ul]:p-0 [&_li]:flex [&_li]:gap-2.5 [&_li]:border-t [&_li]:border-paper [&_li]:py-2 [&_li]:text-[13px] [&_li]:leading-[1.45] [&_li_svg]:mt-0.5 [&_li_svg]:shrink-0 [&_li_svg]:text-text-muted [&_b]:font-bold [&>p]:m-0 [&>p]:text-[13px] [&>p]:text-text-muted',
} satisfies Record<string, string>

export default styles
