// Tailwind classes for TeacherMissionsPage.tsx.
// `teachermissions-*` names carry no styles: they are hooks for the nested selectors in other entries.
const styles = {
  content: 'teachermissions-content mx-auto gap-6 max-w-340 grid [&_:is(a,_button,_input,_select):focus-visible]:[outline:2px_solid_var(--color-primary)] [&_:is(a,_button,_input,_select):focus-visible]:outline-offset-[3px] [&_:is(a,_button,_input,_select):focus-visible]:[scroll-margin-block:80px]',
  header: 'teachermissions-header [&>div:first-child]:min-w-0 [&>div:first-child]:flex-[1_1_280px] py-2 gap-6 flex flex-wrap items-center justify-between [&_h1]:m-0 [&_h1]:text-[32px] [&_h1]:leading-[40px] [&_h1]:font-bold [&_h1]:tracking-[-.035em] [&_p]:mx-0 [&_p]:mt-2 [&_p]:mb-0 [&_p]:text-[14px] [&_p]:leading-[24px] [&_p]:text-text-secondary max-md:gap-4 max-md:items-start max-md:[&_h1]:text-[28px] max-md:[&_h1]:leading-[36px]',
  create: '[.teachermissions-header_&]:px-6 [.teachermissions-header_&]:min-h-12 [.teachermissions-header_&]:rounded-pill [.teachermissions-header_&]:text-[14px] [.teachermissions-header_&]:font-semibold',
  library: 'min-w-0 bg-surface rounded-[24px] max-md:rounded-[20px]',
  libraryHead: 'px-6 pt-6 pb-2 gap-y-2 gap-x-4 flex flex-wrap items-center justify-between [&_h2]:m-0 [&_h2]:text-[18px] [&_h2]:leading-[24px] [&_h2]:font-[650] [&_h2]:tracking-[-.025em] [&>span]:tabular-nums [&>span]:text-text-muted [&>span]:text-[12px] [&>span]:leading-[20px] max-md:px-4',
  filters: 'mx-6 gap-y-2 gap-x-6 [border-bottom-style:solid] border-b border-b-role-border flex flex-wrap [&_button]:px-0 [&_button]:py-3 [&_button]:gap-2 [&_button]:min-h-14 [&_button]:border-none [&_button]:border-0 [&_button]:border-current [&_button]:bg-transparent [&_button]:flex [&_button]:items-center [&_button]:rounded-none [&_button]:text-text-secondary [&_button]:text-[13px] [&_button]:leading-[20px] [&_button]:font-medium [&_button]:[box-shadow:inset_0_-2px_0_transparent] [&_button:hover:not(:disabled)]:bg-transparent [&_button:hover:not(:disabled)]:text-ink [&_button[aria-pressed=true]]:text-primary-hover [&_button[aria-pressed=true]]:font-[650] [&_button[aria-pressed=true]]:[box-shadow:inset_0_-2px_0_var(--color-primary)] [&_button_span]:p-0 [&_button_span]:min-w-0 [&_button_span]:inline-block [&_button_span]:tabular-nums [&_button_span]:rounded-none [&_button_span]:[background:none] [&_button_span]:text-text-secondary [&_button_span]:text-[13px] [&_button_span]:leading-[20px] [&_button_span]:font-bold [&_button[aria-pressed=true]_span]:[background:none] [&_button[aria-pressed=true]_span]:text-primary-hover max-md:mx-4 max-md:gap-0 max-md:grid max-md:grid-cols-[minmax(0,1fr)] max-md:[&_button]:min-h-12 max-md:[&_button]:justify-between',
  toolbar: 'p-6 gap-y-3 gap-x-4 flex flex-wrap items-center max-md:px-4',
  search: 'px-3 gap-3 min-w-0 max-w-110 min-h-11 flex-[1_1_240px] border-solid border border-control-border flex items-center rounded-[12px] text-text-muted [&_input]:px-0 [&_input]:py-2 [&_input]:w-full [&_input]:min-w-0 [&_input]:border-none [&_input]:border-0 [&_input]:border-current [&_input]:bg-transparent [&_input]:text-ink [&_input]:caret-primary [&_input]:[font-family:inherit] [&_input]:text-[14px] [&_input]:leading-[24px] [&_input::placeholder]:text-text-muted [&_input::placeholder]:opacity-100 focus-within:[outline:2px_solid_var(--color-primary)] focus-within:outline-offset-[2px] [.teachermissions-content_&_input:focus-visible]:outline-none [.teachermissions-content_&_input:focus-visible]:[outline-width:0] max-md:max-w-none max-md:flex-[1_1_100%]',
  select: 'gap-2 flex items-center text-text-secondary text-[12px] leading-[20px] [&_select]:px-3 [&_select]:py-2 [&_select]:min-w-0 [&_select]:min-h-11 [&_select]:border [&_select]:border-control-border [&_select]:bg-surface [&_select]:[font-style:inherit] [&_select]:rounded-[12px] [&_select]:text-ink [&_select]:[font-variant:inherit] [&_select]:[font-weight:inherit] [&_select]:[font-stretch:inherit] [&_select]:text-[13px] [&_select]:[line-height:inherit] [&_select]:[font-family:inherit] max-md:flex-[1_1_100%] max-md:[&>span]:min-w-16 max-md:[&_select]:flex-1',
  reset: 'px-0 py-2 min-h-11 border-none bg-transparent text-primary-hover text-[13px] font-semibold hover:not-disabled:bg-transparent hover:not-disabled:underline hover:not-disabled:[text-underline-offset:4px]',
  resultCount: 'mx-6 -mt-2 mb-4 tabular-nums text-text-muted text-[12px] leading-[20px] max-md:mx-4',
  columns: 'mx-6 py-3 gap-8 border-t border-b border-t-role-border border-b-role-border grid items-center grid-cols-[minmax(0,1.65fr)_minmax(180px,1fr)_minmax(180px,.8fr)] text-text-muted text-[12px] leading-[20px] [@media(max-width:1199px)]:hidden',
  row: 'teachermissions-row py-6 gap-8 grid items-center grid-cols-[minmax(0,1.65fr)_minmax(180px,1fr)_minmax(180px,.8fr)] [.teachermissions-row+&]:border-t [.teachermissions-row+&]:border-t-role-border [@media(max-width:1199px)]:gap-y-4 max-md:gap-4 max-md:grid-cols-[minmax(0,1fr)] [@media(max-width:1199px)_and_(width_>_767px)]:gap-x-6 [@media(max-width:1199px)_and_(width_>_767px)]:grid-cols-[minmax(0,1fr)_200px]',
  list: 'm-0 px-6 py-0 list-none [@media(max-width:1199px)]:border-t [@media(max-width:1199px)]:border-t-role-border max-md:px-4',
  identity: 'min-w-0 [&_h3]:m-0 [&_h3]:wrap-anywhere [&_h3]:text-[16px] [&_h3]:leading-[24px] [&_h3]:tracking-[-.02em] [&_h3]:font-semibold [&_p]:mx-0 [&_p]:mt-2 [&_p]:mb-0 [&_p]:wrap-anywhere [&_p]:text-[13px] [&_p]:leading-[20px] [&_p]:text-text-secondary max-md:[&_h3]:text-[17px] max-md:[&_h3]:leading-[26px]',
  version: 'min-w-0 [&_p]:mx-0 [&_p]:mt-1 [&_p]:mb-0 [&_p]:text-text-muted [&_p]:text-[12px] [&_p]:leading-[20px] max-md:col-[auto] [@media(max-width:1199px)_and_(width_>_767px)]:col-[1]',
  name: 'no-underline text-ink rounded-[4px] hover:underline hover:[text-underline-offset:4px]',
  status: 'gap-2 inline-flex items-center wrap-anywhere text-[13px] leading-[20px] font-semibold text-text-secondary data-[status=reviewed]:text-success-strong data-[status=locked]:text-primary-hover data-[status=draft]:text-warning-text',
  actions: 'teachermissions-actions gap-1 min-w-0 grid justify-items-stretch [&_a]:px-3 [&_a]:py-2 [&_a]:gap-2 [&_a]:min-h-11 [&_a]:flex [&_a]:items-center [&_a]:whitespace-nowrap [&_a]:no-underline [&_a]:text-primary-hover [&_a]:rounded-[8px] [&_a]:text-[12px] [&_a]:leading-[20px] [&_a]:font-semibold [&_a>svg]:ml-auto max-md:col-[auto] max-md:row-[auto] max-md:[&_a]:text-[13px] [@media(max-width:1199px)_and_(width_>_767px)]:col-[2] [@media(max-width:1199px)_and_(width_>_767px)]:row-[1_/_3]',
  publish: '[.teachermissions-actions_&]:bg-info-bg [.teachermissions-actions_&]:[transition:background-color_140ms_ease-out] [.teachermissions-actions_&:hover]:bg-nav-hover motion-reduce:[.teachermissions-actions_&]:[transition:none]',
  primaryAction: '[.teachermissions-actions_&]:bg-info-bg [.teachermissions-actions_&]:[transition:background-color_140ms_ease-out] [.teachermissions-actions_&:hover]:bg-nav-hover motion-reduce:[.teachermissions-actions_&]:[transition:none]',
  secondaryAction: '[.teachermissions-actions_&]:font-medium [.teachermissions-actions_&:hover]:underline [.teachermissions-actions_&:hover]:[text-underline-offset:4px]',
  note: 'mx-6 my-0 px-0 pt-4 pb-6 gap-2 border-t border-t-role-border flex items-center text-[12px] leading-[20px] text-text-muted max-md:mx-4',
  emptyAction: '[.teachermissions-content_&]:px-4 [.teachermissions-content_&]:py-3 [.teachermissions-content_&]:min-h-11 [.teachermissions-content_&]:rounded-pill [.teachermissions-content_&]:text-[13px] [button&]:border [button&]:border-control-border [button&]:bg-surface [button&]:text-primary-hover [button&]:font-semibold [button&:hover:not(:disabled)]:bg-nav-hover',
  loading: 'px-6 pt-2 pb-6 text-text-secondary text-[14px] max-md:px-4',
  skeleton: '[&>div]:py-6 [&>div]:gap-8 [&>div]:grid [&>div]:grid-cols-[1.65fr_1fr_.8fr] [&>div+div]:border-t [&>div+div]:border-t-role-border [&_span]:h-12 [&_span]:bg-surface-muted [&_span]:rounded-[8px] max-md:[&>div]:gap-3 max-md:[&>div]:grid-cols-[1fr] max-md:[&_span]:h-8',
} satisfies Record<string, string>

export default styles
