// Tailwind classes for TeacherClassMapPage.tsx.
// `teacherclassmap-*` names carry no styles: they are hooks for the nested selectors in other entries.
const styles = {
  content: 'mx-auto max-w-340',
  back: 'min-h-11 inline-flex items-center text-[13px] font-semibold text-text-secondary',
  header: 'gap-4 flex flex-wrap items-end justify-between [&_h1]:m-0 [&_h1]:text-[22px] [&_h1]:leading-[30px] [&_h1]:tracking-[-.015em] [&_p]:mx-0 [&_p]:mt-0.5 [&_p]:mb-0 [&_p]:text-[13px] [&_p]:text-text-muted',
  actions: 'gap-2 flex flex-wrap [&_button]:min-h-9 [&_button]:px-3.5 [&_button]:py-1.5 max-md:[&_button]:min-h-11 [&_button]:gap-1.5 [&_button]:whitespace-nowrap [&_button]:text-[13px] [&_button]:rounded-[8px]',
  release: 'px-4 gap-1.5 min-h-9 max-md:min-h-11 bg-primary inline-flex items-center justify-center whitespace-nowrap no-underline rounded-[8px] text-surface text-[13px] font-semibold hover:bg-primary-hover',
  note: 'mx-0 mt-2 mb-0 max-w-[72ch] text-[13px] leading-[20px] text-text-secondary',
  kpis: 'mx-0 mt-5 mb-0 gap-3 grid [&>div]:rounded-xl [&>div]:bg-surface grid-cols-[repeat(auto-fit,minmax(150px,1fr))] [&>div]:px-5 [&>div]:py-4 [&>div]:min-w-0 [&_dt]:text-[11px] [&_dt]:font-semibold [&_dt]:tracking-[.06em] [&_dt]:text-text-muted [&_dd]:mx-0 [&_dd]:mt-1 [&_dd]:mb-0 [&_dd]:gap-2 [&_dd]:flex [&_dd]:flex-wrap [&_dd]:items-center [&_strong]:text-[20px] [&_dd_span]:px-[7px] [&_dd_span]:py-0.5 [&_dd_span]:whitespace-nowrap [&_dd_span]:rounded-[999px] [&_dd_span]:text-[11px] [&_dd_span]:font-semibold [&_span[data-tone=info]]:bg-info-bg [&_span[data-tone=info]]:text-primary-hover [&_span[data-tone=misconception]]:bg-misconception-bg [&_span[data-tone=misconception]]:text-misconception-text [&_span[data-tone=success]]:bg-success-bg [&_span[data-tone=success]]:text-success-strong [&_span[data-tone=verification]]:bg-verification-bg [&_span[data-tone=verification]]:text-ink [@media(max-width:560px)]:[&>div+div]:[border-top-style:solid] [@media(max-width:560px)]:[&>div+div]:[border-left-style:none] [@media(max-width:560px)]:[&>div+div]:border-t [@media(max-width:560px)]:[&>div+div]:border-l-0 [@media(max-width:560px)]:[&>div+div]:border-t-role-border [@media(max-width:560px)]:[&>div+div]:border-l-current',
  grid: 'mt-4 gap-4 grid items-start grid-cols-[minmax(0,2fr)_minmax(0,1fr)] [@media(max-width:900px)]:grid-cols-[minmax(0,1fr)]',
  card: 'p-4 min-w-0 bg-surface rounded-2xl [&_h2]:m-0 [&_h2]:text-[14px] [&_h2]:leading-[22px]',
  table: '[&_h2]:m-0 [&_h2]:px-4 [&_h2]:py-3 [&_h2]:gap-2 [&_h2]:border-b [&_h2]:border-b-role-border [&_h2]:flex [&_h2]:items-center [&_h2]:text-[14px] [&_h2]:leading-[22px] mt-4 bg-surface overflow-hidden rounded-2xl [&_h2_span]:px-[7px] [&_h2_span]:py-px [&_h2_span]:border [&_h2_span]:border-role-border [&_h2_span]:rounded-[999px] [&_h2_span]:text-[11px] [&_h2_span]:font-semibold',
  cardHead: 'gap-y-2 gap-x-3 flex flex-wrap items-center justify-between [&_h2]:gap-2 [&_h2]:flex [&_h2]:items-center',
  legend: "m-0 p-0 gap-y-1 gap-x-3 flex flex-wrap list-none text-[12px] text-text-secondary [&_li]:gap-1.5 [&_li]:flex [&_li]:items-center [&_li::before]:w-2 [&_li::before]:h-2 [&_li::before]:bg-primary [&_li::before]:content-[''] [&_li::before]:rounded-[50%] [&_li[data-kind=developing]::before]:bg-accent [&_li[data-kind=misconception]::before]:bg-misconception-text",
  system: 'mx-0 mt-3 mb-0 px-3 py-2 gap-y-1 gap-x-2 bg-success-bg flex flex-wrap rounded-[8px] text-[12px] text-text-secondary [&_strong]:tracking-[.04em] [&_strong]:text-success-strong',
  mapRegion: 'mt-3 relative overflow-x-auto rounded-[10px]',
  map: 'h-90 min-w-130 relative rounded-[10px] [background:var(--color-canvas)_radial-gradient(var(--color-border)_1px,transparent_1px)_0_0_/_16px_16px] [&_svg]:inset-0 [&_svg]:w-full [&_svg]:h-full [&_svg]:absolute [&_path]:[fill:none] [&_path]:stroke-text-muted [&_path]:[stroke-width:1.25] [&_path]:opacity-50 [&_path]:[vector-effect:non-scaling-stroke] [&_ul]:m-0 [&_ul]:p-0 [&_ul]:list-none [&_li]:px-3 [&_li]:py-2.5 [&_li]:w-37.5 [&_li]:border [&_li]:border-role-border [&_li]:bg-surface [&_li]:absolute [&_li]:[transform:translate(-50%,-50%)] [&_li]:rounded-[10px] [&_li_strong]:block [&_li_strong]:text-[12px] [&_small]:mt-1 [&_small]:block [&_small]:text-[11px] [&_small]:text-text-muted',
  bar: 'mt-1.5 h-1.5 bg-role-border overflow-hidden flex rounded-[3px] [&_span:nth-child(1)]:bg-primary [&_span:nth-child(2)]:bg-accent [&_span:nth-child(3)]:bg-misconception-text',
  story: 'mx-0 mt-2.5 mb-0 text-[13px] leading-[21px] [&_b]:px-1.5 [&_b]:py-0 [&_b]:bg-paper [&_b]:rounded-[4px] [&_b[data-kind=held]]:bg-misconception-bg [&_b[data-kind=held]]:text-misconception-text [&_b[data-kind=changed]]:bg-success-bg [&_b[data-kind=changed]]:text-success-strong',
  eyebrow: 'mx-0 mt-4 mb-0 text-[11px] font-semibold tracking-[.06em] text-text-muted',
  suggestions: 'mx-0 mt-1.5 mb-0 py-0 pr-0 pl-5 gap-2 grid list-none text-[13px] leading-[21px] [&_li]:px-3 [&_li]:py-2.5 [&_li]:bg-warning-bg [&_li]:rounded-[8px] [&_li]:text-[12px] [&_li]:leading-[18px] [&_li+li]:mt-1',
  tableRegion: 'teacherclassmap-tableRegion relative overflow-x-auto [&_table]:w-full [&_table]:min-w-180 [&_table]:border-collapse [&_table]:text-[13px] [&_caption]:w-px [&_caption]:h-px [&_caption]:overflow-hidden [&_caption]:absolute [&_caption]:[clip-path:inset(50%)] [&_thead_th]:px-4 [&_thead_th]:py-2.5 [&_thead_th]:bg-canvas [&_thead_th]:text-start [&_thead_th]:text-[11px] [&_thead_th]:font-semibold [&_thead_th]:tracking-[.06em] [&_thead_th]:text-text-muted [&_tbody_th]:px-4 [&_tbody_th]:py-3 [&_tbody_th]:text-start [&_tbody_th]:font-semibold [&_td]:px-4 [&_td]:py-3 [&_td]:text-text-secondary [&_tbody_tr]:border-t [&_tbody_tr]:border-t-surface-muted [&_td_button]:whitespace-nowrap [&_td_button]:text-[12px] [&_td_button]:rounded-[8px]',
  held: '[.teacherclassmap-tableRegion_&]:font-bold [.teacherclassmap-tableRegion_&]:text-misconception-text',
  progress: 'gap-2 flex items-center text-[12px] [&>span]:h-1.5 [&>span]:flex-[0_1_140px] [&>span]:bg-paper [&>span]:overflow-hidden [&>span]:rounded-[3px] [&_i]:h-full [&_i]:bg-success-text [&_i]:block',
  hidden: 'm-0 p-0 w-px h-px overflow-hidden absolute [clip-path:inset(50%)]',
  suggestTitle: 'mx-0 mt-4 mb-0 text-[13px] leading-[20px]',
} satisfies Record<string, string>

export default styles
