// Tailwind classes for NalaHero.tsx.
// `nalahero-*` names carry no styles: they are hooks for the nested selectors in other entries.
const styles = {
  hero: 'pt-[calc(var(--header-height)_+_clamp(12px,2.4vw,32px))] pb-[clamp(56px,7vw,96px)] [--tinta:#2447D1] [--stage-h:520px] [--nala-x:38%] [@media(min-width:1024px)_and_(max-height:820px)]:[--stage-h:452px] max-sm:[--stage-h:420px] max-sm:[--nala-x:50%]',
  grid: 'gap-10 grid items-center lg:gap-12 lg:grid-cols-[minmax(0,0.92fr)_minmax(0,1.08fr)]',
  // Stage: Nala in a line-drawn NALAR doorway on the paper itself, no colour block behind her.
  figure: 'max-lg:order-[-1] m-0 gap-3 grid relative',
  // Copy
  copy: 'gap-5 max-w-135 grid justify-items-start [animation:nalahero-lift_800ms_var(--ease-out)_both] motion-reduce:[animation:none]!',
  title: 'm-0 text-balance text-[clamp(2.5rem,1.45rem_+_2.95vw,3.6rem)] font-extrabold leading-[1.04] tracking-[-0.036em] [@media(min-width:1024px)_and_(max-height:820px)]:text-[clamp(2.5rem,1.4rem_+_2.5vw,3.1rem)]',
  mark: 'mx-[-0.06em] px-[0.06em] [background-image:linear-gradient(var(--highlight),var(--highlight))] [background-position:0_86%] [background-size:100%_0.34em] [background-repeat:no-repeat] [box-decoration-break:clone] [animation:nalahero-sweep_900ms_var(--ease-out)_700ms_both] motion-reduce:[animation:none]!',
  lead: 'max-w-[31rem] text-pretty text-text-secondary text-[1.125rem] leading-[1.6]',
  actions: 'mt-3 gap-y-2 gap-x-4 flex flex-wrap items-center',
  ghost: 'px-2 gap-1.5 min-h-13 inline-flex items-center no-underline text-ink text-[1.0625rem] font-[650] [transition:color_160ms_ease] [&_svg]:[transition:transform_200ms_var(--ease-out)] [@media(hover:hover)_and_(pointer:fine)]:hover:text-primary [@media(hover:hover)_and_(pointer:fine)]:[&:hover_svg]:[transform:translateX(3px)]',
  stage: 'nalahero-stage h-[var(--stage-h)] relative [&[data-paused=true]_*]:[animation-play-state:paused]!',
  layer: 'inset-0 absolute pointer-events-none [will-change:transform]',
  arch: 'ml-[-165px] bottom-6 left-[var(--nala-x)] w-82.5 h-[403px] overflow-visible absolute [@media(min-width:1024px)_and_(max-height:820px)]:-ml-35 [@media(min-width:1024px)_and_(max-height:820px)]:w-70 [@media(min-width:1024px)_and_(max-height:820px)]:h-85.5 max-sm:-ml-30 max-sm:bottom-0 max-sm:w-60 max-sm:h-[293px]',
  floor: 'fill-[color-mix(in_srgb,var(--color-accent)_20%,var(--color-paper))] [transform-box:fill-box] [transform-origin:center] [animation:nalahero-grow_900ms_var(--ease-out)_200ms_both] motion-reduce:[animation:none]!',
  archPath: '[fill:none] [stroke-linecap:round] [stroke-dasharray:100] [stroke:var(--tinta)] [stroke-width:9] [animation:nalahero-draw_1500ms_var(--ease-in-out)_300ms_both] motion-reduce:[animation:none]!',
  archEcho: '[fill:none] [stroke-linecap:round] [stroke-dasharray:100] stroke-[rgb(36_71_209_/_16%)] [stroke-width:2.5] [animation:nalahero-draw_1700ms_var(--ease-in-out)_620ms_both] motion-reduce:[animation:none]!',
  // Only the mascot's own motion keeps a slight spring; every UI piece eases out.
  sun: 'fill-accent [transform-box:fill-box] [transform-origin:center] [animation:nalahero-pop_560ms_cubic-bezier(0.34,1.25,0.64,1)_1200ms_both,nalahero-float_5s_ease-in-out_1.8s_infinite] motion-reduce:[animation:none]!',
  nala: 'bottom-12.5 left-[var(--nala-x)] absolute [translate:-50%_0] [animation:nalahero-drop_760ms_cubic-bezier(0.34,1.25,0.64,1)_640ms_both] [@media(min-width:1024px)_and_(max-height:820px)]:bottom-11 [@media(min-width:1024px)_and_(max-height:820px)]:[&_svg]:w-50 [@media(min-width:1024px)_and_(max-height:820px)]:[&_svg]:h-auto max-sm:bottom-4.5 max-sm:[&_svg]:w-40 max-sm:[&_svg]:h-auto motion-reduce:[animation:none]!',
  thinking: 'px-3 py-2.5 top-1.5 -right-2.5 gap-[5px] bg-surface flex absolute rounded-[999px] [box-shadow:0_10px_24px_rgb(21_33_59_/_18%)] opacity-0 [transform:translateY(6px)_scale(0.92)] [transition:opacity_200ms_ease,transform_200ms_var(--ease-out)] [&_span]:w-[7px] [&_span]:h-[7px] [&_span]:rounded-[50%] [&_span]:[background:var(--tinta)] [&_span]:[animation:nalahero-dot_1s_ease-in-out_infinite] [&_span:nth-child(2)]:[animation-delay:150ms] [&_span:nth-child(3)]:[animation-delay:300ms] [.nalahero-stage[data-scene=think]_&]:opacity-100 [.nalahero-stage[data-scene=think]_&]:[transform:none] [.nalahero-stage[data-scene=think]_&]:[transition-delay:700ms] motion-reduce:[&_span]:[animation:none]!',
  // Cards: hidden states exit fast, visible states enter slower and later.
  ask: 'px-5 py-4.5 top-0 left-0 gap-3 w-[min(360px,68%)] bg-surface grid absolute [transition:opacity_220ms_ease,transform_220ms_var(--ease-out),filter_220ms_ease] [border-radius:20px_20px_20px_6px] [box-shadow:0_1px_2px_rgb(21_33_59_/_6%),0_28px_56px_-22px_rgb(21_33_59_/_30%)] [animation:nalahero-rise_760ms_var(--ease-out)_1000ms_both] max-sm:inset-x-0 max-sm:top-0 max-sm:w-auto max-sm:[.nalahero-stage:is([data-scene=think],_[data-scene=evidence])_&]:opacity-0 max-sm:[.nalahero-stage:is([data-scene=think],_[data-scene=evidence])_&]:[transform:translateY(-8px)] max-sm:[.nalahero-stage:is([data-scene=think],_[data-scene=evidence])_&]:[filter:blur(4px)] motion-reduce:[animation:none]! motion-reduce:[transition:none]!',
  // Cards: hidden states exit fast, visible states enter slower and later.
  answer: 'px-4.5 py-4 top-37 right-0 gap-1.5 w-[min(236px,44%)] bg-info-bg grid absolute [transition:opacity_220ms_ease,transform_220ms_var(--ease-out),filter_220ms_ease] [border-radius:20px_6px_20px_20px] [box-shadow:0_22px_44px_-22px_rgb(10_20_60_/_55%)] opacity-0 [transform:translateX(18px)] [filter:blur(4px)] [&_p]:font-reading [&_p]:text-[0.9375rem] [&_p]:leading-[1.55] [.nalahero-stage:is([data-scene=think],_[data-scene=evidence])_&]:opacity-100 [.nalahero-stage:is([data-scene=think],_[data-scene=evidence])_&]:[transform:none] [.nalahero-stage:is([data-scene=think],_[data-scene=evidence])_&]:[filter:none] [.nalahero-stage:is([data-scene=think],_[data-scene=evidence])_&]:[transition:opacity_460ms_ease_260ms,transform_520ms_var(--ease-out)_260ms,filter_460ms_ease_260ms] [@media(min-width:1024px)_and_(max-height:820px)]:top-32 max-sm:inset-x-0 max-sm:top-0 max-sm:w-auto max-sm:[transform:translateY(12px)] max-sm:[.nalahero-stage[data-scene=evidence]_&]:opacity-0 max-sm:[.nalahero-stage[data-scene=evidence]_&]:[transform:translateY(-8px)] max-sm:[.nalahero-stage[data-scene=evidence]_&]:[filter:blur(4px)] max-sm:[.nalahero-stage[data-scene=evidence]_&]:[transition:opacity_220ms_ease,transform_220ms_var(--ease-out),filter_220ms_ease] motion-reduce:[transition:none]!',
  // Cards: hidden states exit fast, visible states enter slower and later.
  count: 'py-3 pr-3.5 pl-3 bottom-1.5 left-0 gap-3 w-[min(236px,44%)] bg-surface flex absolute items-center [transition:opacity_220ms_ease,transform_220ms_var(--ease-out),filter_220ms_ease] rounded-[16px] [box-shadow:0_22px_44px_-22px_rgb(10_20_60_/_55%)] text-[0.8125rem] leading-[1.35] text-text-secondary opacity-0 [transform:translateY(14px)_scale(0.96)] [filter:blur(4px)] [&_strong]:block [&_strong]:text-ink [&_strong]:text-[0.875rem] [.nalahero-stage[data-scene=evidence]_&]:opacity-100 [.nalahero-stage[data-scene=evidence]_&]:[transform:none] [.nalahero-stage[data-scene=evidence]_&]:[filter:none] [.nalahero-stage[data-scene=evidence]_&]:[transition:opacity_460ms_ease_480ms,transform_560ms_var(--ease-out)_480ms,filter_460ms_ease_480ms] max-sm:hidden motion-reduce:[transition:none]!',
  // Cards: hidden states exit fast, visible states enter slower and later.
  evidence: 'px-5 py-4.5 right-0 bottom-0 gap-2.5 w-[min(252px,46%)] grid absolute [transition:opacity_220ms_ease,transform_220ms_var(--ease-out),filter_220ms_ease] rounded-[20px] text-[#FFFFFF] [background:var(--projector)] [box-shadow:0_30px_56px_-18px_rgb(10_20_60_/_60%)] opacity-0 [transform:translateY(18px)] [filter:blur(4px)] [&_p]:text-[#E4E8F2] [&_p]:font-reading [&_p]:text-[0.9375rem] [&_p]:leading-[1.45] [&_mark]:text-inherit [&_mark]:[background:linear-gradient(rgb(242_178_58_/_38%),rgb(242_178_58_/_38%))_no-repeat_0_88%_/_100%_55%] [.nalahero-stage[data-scene=evidence]_&]:opacity-100 [.nalahero-stage[data-scene=evidence]_&]:[transform:none] [.nalahero-stage[data-scene=evidence]_&]:[filter:none] [.nalahero-stage[data-scene=evidence]_&]:[transition:opacity_460ms_ease_200ms,transform_560ms_var(--ease-out)_200ms,filter_460ms_ease_200ms] max-sm:inset-x-0 max-sm:top-0 max-sm:bottom-auto max-sm:w-auto motion-reduce:[transition:none]!',
  askHead: 'gap-3 flex items-center justify-between',
  who: 'gap-2 inline-flex items-center text-[0.875rem] font-bold',
  progress: 'gap-1 inline-flex items-center opacity-0 [transition:opacity_240ms_ease] [&_i]:w-4 [&_i]:h-[5px] [&_i]:bg-surface-muted [&_i]:rounded-[3px] [&_i[data-on=true]]:[background:var(--tinta)] [&_b]:ml-1.5 [&_b]:whitespace-nowrap [&_b]:text-text-muted [&_b]:text-[0.75rem] [&_b]:font-semibold [.nalahero-stage:not([data-scene=hello])_&]:opacity-100 motion-reduce:[transition:none]!',
  lines: 'grid [&_p]:text-pretty [&_p]:[grid-area:1_/_1] [&_p]:text-[1.0625rem] [&_p]:font-medium [&_p]:leading-[1.55] [&_p]:[transition:opacity_260ms_ease,filter_260ms_ease,transform_260ms_var(--ease-out)] motion-reduce:[&_p]:[transition:none]!',
  probe: 'opacity-0 [filter:blur(4px)] [transform:translateY(6px)] [.nalahero-stage:not([data-scene=hello])_&]:opacity-100 [.nalahero-stage:not([data-scene=hello])_&]:[filter:none] [.nalahero-stage:not([data-scene=hello])_&]:[transform:none] [.nalahero-stage:not([data-scene=hello])_&]:[transition-delay:120ms]',
  answerWho: '[color:var(--tinta)] text-[0.75rem] font-bold',
  countNumber: 'w-10 h-10 flex-none bg-misconception-bg grid items-center justify-items-center tabular-nums rounded-[12px] text-misconception-text text-[1rem] font-extrabold',
  evidenceHead: 'flex items-baseline justify-between [&_span]:[color:var(--projector-muted)] [&_span]:text-[0.8125rem] [&_span]:font-semibold [&_b]:text-[1.5rem] [&_b]:font-extrabold [&_b]:tracking-[-0.02em] [&_small]:text-[#8792AB] [&_small]:text-[1rem]',
  evidenceFoot: 'text-[#8792AB] text-[0.75rem]',
  // Scenes
  greeting: '[.nalahero-stage:not([data-scene=hello])_&]:opacity-0 [.nalahero-stage:not([data-scene=hello])_&]:[filter:blur(4px)] [.nalahero-stage:not([data-scene=hello])_&]:[transform:translateY(-6px)]',
} satisfies Record<string, string>

export default styles
