// Tailwind classes for AccessTable.tsx, Checkpoints.tsx, ClassMap.tsx, DialogueStory.tsx, EvidenceReport.tsx, Faq.tsx, Landing.tsx, LandingMenu.tsx, NalaHero.tsx, ProjectorSection.tsx.
// `landing-*` names carry no styles: they are hooks for the nested selectors in other entries.
const styles = {
  // Reveal grammar: a heading rises out of a clip mask and what follows it fades up after.
  page: 'min-h-dvh bg-paper overflow-x-clip [--ease-out:cubic-bezier(0.23,1,0.32,1)] [--ease-in-out:cubic-bezier(0.77,0,0.175,1)] [--projector:#15213B] [--projector-raised:#1E2C4D] [--projector-ink:#E8ECF6] [--projector-muted:#A9B3CB] [--highlight:rgb(242_178_58_/_46%)] [--header-height:76px] text-ink [html:has(&)]:bg-paper [html:has(&)]:[scroll-padding-block-start:calc(var(--header-height)_+_16px)] [html:has(&)]:[scrollbar-color:var(--color-control-border)_var(--color-paper)] motion-safe:[html:has(&)]:[scroll-behavior:smooth] [&_::selection]:text-ink [&_::selection]:[background:var(--highlight)] [&_:focus-visible]:[outline:3px_solid_var(--color-primary)] [&_:focus-visible]:outline-offset-[3px] [&_:focus-visible]:rounded-[6px] [:where(&)_p]:m-0 [:where(&)_p]:text-inherit [:where(&)_:is(h2,_h3)]:m-0 [&_[data-reveal]>:is(h2,_p,_div)]:[transition:opacity_700ms_var(--ease-out),transform_820ms_var(--ease-out),clip-path_900ms_var(--ease-out)] [&_[data-reveal]>:nth-child(2)]:[transition-delay:110ms] [&_[data-reveal]>:nth-child(3)]:[transition-delay:200ms] [&_[data-reveal]>:nth-child(4)]:[transition-delay:280ms] [&_[data-reveal]>h2]:[clip-path:inset(-20%_-6%_-24%_-6%)] [&_[data-reveal][data-in=false]>h2]:[clip-path:inset(-20%_-6%_100%_-6%)] [&_[data-reveal][data-in=false]>h2]:[transform:translateY(0.4em)] [&_[data-reveal][data-in=false]>:is(p,_div)]:opacity-0 [&_[data-reveal][data-in=false]>:is(p,_div)]:[transform:translateY(18px)]',
  wrap: 'mx-auto px-4 w-full max-w-308 sm:px-6 lg:px-8',
  skip: 'px-4 py-3 top-2 left-2 bg-ink absolute z-40 rounded-[10px] text-surface font-semibold [transform:translateY(-160%)] [transition:transform_160ms_var(--ease-out)] focus-visible:[transform:none]',
  // Header: the previous landing's floating bar. Full width at the top, an island pill once the page scrolls.
  sentinel: 'top-0 w-px h-4 absolute',
  navbar: 'landing-navbar px-11 py-4 top-0 left-[50%] w-full max-w-full border border-t-transparent border-r-transparent border-b-[rgb(228_224_215_/_70%)] border-l-transparent block fixed z-30 rounded-none [background:color-mix(in_srgb,var(--color-paper)_90%,transparent)] [box-shadow:none] [transform:translateX(-50%)] [backdrop-filter:blur(16px)] [transition-property:inset-block-start,inline-size,max-inline-size,padding,border-radius,border-color,background-color,box-shadow] [transition-duration:400ms] [transition-timing-function:cubic-bezier(0.16,1,0.3,1)] data-[scrolled=true]:px-5.5 data-[scrolled=true]:py-2 data-[scrolled=true]:top-3.5 data-[scrolled=true]:w-[calc(100%_-_36px)] data-[scrolled=true]:max-w-275 data-[scrolled=true]:border-t-[rgb(36_71_209_/_12%)] data-[scrolled=true]:border-r-[rgb(36_71_209_/_12%)] data-[scrolled=true]:border-b-[rgb(36_71_209_/_14%)] data-[scrolled=true]:border-l-[rgb(36_71_209_/_12%)] data-[scrolled=true]:bg-[rgb(255_255_255_/_95%)] data-[scrolled=true]:rounded-[999px] data-[scrolled=true]:[box-shadow:0_14px_34px_-8px_rgb(36_71_209_/_16%),0_2px_8px_rgb(36_71_209_/_4%)] data-[scrolled=true]:[backdrop-filter:blur(20px)] [@media(max-width:600px)]:px-4.5 [@media(max-width:600px)]:py-3 [@media(max-width:600px)]:data-[scrolled=true]:px-3.5 [@media(max-width:600px)]:data-[scrolled=true]:py-2 [@media(max-width:600px)]:data-[scrolled=true]:top-2.5 [@media(max-width:600px)]:data-[scrolled=true]:w-[calc(100%_-_20px)]',
  navInner: 'mx-auto gap-5 w-full max-w-300 flex items-center justify-between [.landing-navbar[data-scrolled=true]_&]:gap-4',
  navBrand: 'gap-2 min-h-11 inline-flex items-center select-none no-underline text-ink text-[1.45rem] font-extrabold tracking-[-0.04em] [transition:font-size_300ms_ease,transform_200ms_var(--ease-out)] [.landing-navbar[data-scrolled=true]_&]:text-[1.25rem] [@media(hover:hover)_and_(pointer:fine)]:hover:[transform:scale(1.02)]',
  brandDot: 'text-primary',
  navRightGroup: 'gap-3.5 flex items-center',
  navLinks: 'px-1 py-[3px] gap-0.5 border border-[rgb(36_71_209_/_6%)] bg-[rgb(36_71_209_/_3%)] hidden items-center rounded-[999px] [@media(min-width:1040px)]:flex',
  navLink: 'px-[13px] py-[7px] whitespace-nowrap no-underline rounded-[999px] text-text-secondary text-[0.85rem] font-semibold [transition:color_200ms_ease,background-color_200ms_ease] aria-[current=true]:bg-[rgb(36_71_209_/_9%)] aria-[current=true]:text-primary aria-[current=true]:font-bold [@media(hover:hover)_and_(pointer:fine)]:hover:bg-[rgb(21_33_59_/_5%)] [@media(hover:hover)_and_(pointer:fine)]:hover:text-ink [@media(hover:hover)_and_(pointer:fine)]:aria-[current=true]:hover:bg-[rgb(36_71_209_/_14%)] [@media(hover:hover)_and_(pointer:fine)]:aria-[current=true]:hover:text-primary',
  navCtaPill: 'px-4.5 py-2 gap-1.5 min-h-10 bg-primary inline-flex items-center whitespace-nowrap no-underline rounded-[999px] text-[#FFFFFF] text-[0.85rem] font-bold [box-shadow:0_4px_14px_rgb(36_71_209_/_25%)] [transition:background-color_200ms_ease,box-shadow_220ms_ease,transform_220ms_var(--ease-out)] active:[transform:scale(0.98)] [@media(hover:hover)_and_(pointer:fine)]:hover:bg-primary-hover [@media(hover:hover)_and_(pointer:fine)]:hover:[box-shadow:0_6px_18px_rgb(36_71_209_/_35%)] [@media(hover:hover)_and_(pointer:fine)]:hover:[transform:translateY(-1px)_scale(1.02)] [@media(max-width:379px)]:hidden',
  menuButton: 'p-0 w-10 min-h-10 border border-[rgb(36_71_209_/_10%)] bg-[rgb(36_71_209_/_3%)] inline-grid items-center justify-items-center rounded-[999px] text-ink hover:not-disabled:bg-[rgb(36_71_209_/_9%)] hover:not-disabled:text-primary [@media(min-width:1040px)]:hidden',
  // The footer keeps the plain wordmark.
  brand: 'gap-2 min-h-11 inline-flex items-center no-underline text-ink text-[1.375rem] font-extrabold tracking-[-0.04em] [.landing-footerInner_&]:text-[1.125rem]',
  drawerNav: 'landing-drawerNav gap-1 grid [&_a]:px-3 [&_a]:min-h-13 [&_a]:flex [&_a]:items-center [&_a]:no-underline [&_a]:rounded-[10px] [&_a]:text-ink [&_a]:text-[1.125rem] [&_a]:font-semibold [&_a:hover]:bg-surface-muted',
  login: '[.landing-drawerNav_&]:mt-4 [.landing-drawerNav_&]:bg-primary [.landing-drawerNav_&]:justify-center [.landing-drawerNav_&]:text-surface [.landing-drawerNav_&:hover]:bg-primary-hover',
  // Actions: one radius rule for every control on the page (12px), objects use 20-24px.
  primary: 'px-5.5 gap-2.5 min-h-13 bg-primary inline-flex items-center justify-center whitespace-nowrap no-underline rounded-[12px] text-[1.0625rem] font-[650] [transition:background-color_160ms_ease,transform_160ms_var(--ease-out)] text-surface [&_svg]:[transition:transform_200ms_var(--ease-out)] active:[transform:scale(0.97)] [@media(hover:hover)_and_(pointer:fine)]:hover:bg-primary-hover [@media(hover:hover)_and_(pointer:fine)]:[&:hover_svg]:[transform:translateX(3px)]',
  // Actions: one radius rule for every control on the page (12px), objects use 20-24px.
  secondary: 'px-5.5 gap-2.5 min-h-13 bg-surface-muted inline-flex items-center justify-center whitespace-nowrap no-underline rounded-[12px] text-[1.0625rem] font-[650] [transition:background-color_160ms_ease,transform_160ms_var(--ease-out)] text-ink active:[transform:scale(0.97)] [@media(hover:hover)_and_(pointer:fine)]:hover:bg-border',
  // Section rhythm
  section: 'py-[clamp(64px,9vw,136px)]',
  head: 'mb-[clamp(40px,5vw,64px)] gap-4 max-w-[44rem] grid',
  h2: 'text-balance text-[clamp(2rem,1.35rem_+_2.2vw,3rem)] font-[750] leading-[1.1] tracking-[-0.032em]',
  lead: 'max-w-[58ch] text-pretty text-text-secondary text-[1.125rem] leading-[1.6] [.landing-closingCopy_&]:max-w-[44ch]',
  caption: 'mt-6 text-text-muted text-[0.8125rem] leading-[1.5]',
  // Closing and footer
  closing: 'pt-[clamp(64px,9vw,128px)] pb-[clamp(48px,7vw,96px)]',
  closingGrid: 'landing-closingGrid gap-10 grid items-end [@media(min-width:900px)]:grid-cols-[minmax(0,1fr)_auto]',
  closingTitle: 'max-w-[14ch] text-balance text-[clamp(2.5rem,1.5rem_+_3.4vw,4.25rem)] font-extrabold leading-[1.04] tracking-[-0.032em]',
  closingCopy: 'landing-closingCopy gap-6 grid justify-items-start',
  note: 'text-text-muted text-[0.9375rem]',
  // Closing bookend: the board's iconic Nala, on a Kertas disc inside a Tinta circle.
  bookend: "[@media(min-width:900px)]:mr-8 w-[min(300px,78vw)] grid relative items-center justify-items-center [justify-self:start] aspect-[1] [&::before]:inset-0 [&::before]:bg-[#2447D1] [&::before]:[background-image:radial-gradient(rgb(255_255_255_/_10%)_1.2px,transparent_1.7px)] [&::before]:[background-size:20px_20px] [&::before]:absolute [&::before]:content-[''] [&::before]:rounded-[50%] [&::before]:[box-shadow:0_40px_70px_-36px_rgb(36_71_209_/_60%)] [&::before]:[transition:transform_900ms_var(--ease-out),opacity_600ms_ease] [.landing-closingGrid[data-in=false]_&::before]:opacity-0 [.landing-closingGrid[data-in=false]_&::before]:[transform:scale(0.7)]",
  footer: 'pt-8 pb-10',
  footerInner: 'landing-footerInner pt-6 gap-y-2 gap-x-6 border-t border-t-border flex flex-wrap items-center text-text-muted text-[0.875rem]',
  footerLink: 'ml-auto text-ink font-semibold [text-underline-offset:4px]',
  bookendDisc: 'inset-[13%] bg-paper absolute rounded-[50%] [transition:transform_900ms_var(--ease-out)_120ms,opacity_600ms_ease_120ms] [.landing-closingGrid[data-in=false]_&]:opacity-0 [.landing-closingGrid[data-in=false]_&]:[transform:scale(0.6)]',
  bookendSun: 'top-[9%] right-[11%] w-[12%] bg-accent absolute aspect-[1] rounded-[50%] [animation:landing-bookendFloat_5s_ease-in-out_infinite] motion-reduce:[animation:none]',
  bookendNala: 'mt-[12%] relative [transition:transform_760ms_cubic-bezier(0.34,1.25,0.64,1)_300ms,opacity_400ms_ease_300ms] [&_svg]:w-[clamp(150px,46vw,190px)] [&_svg]:h-auto [.landing-closingGrid[data-in=false]_&]:opacity-0 [.landing-closingGrid[data-in=false]_&]:[transform:translateY(-28px)]',
} satisfies Record<string, string>

export default styles
