// Tailwind classes for LiveStudentLobby.tsx.
const styles = {
  // The supplied live-class look uses one extra decorative orange; it never signals correctness.
  page: 'mx-auto my-0 px-12 pt-8 pb-16 max-w-340 [--lobby-orange:#E7794A] max-md:px-4 max-md:pt-6 max-md:pb-12 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:px-10 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:pt-5 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:pb-12',
  back: 'min-h-11 inline-flex items-center font-semibold',
  welcome: 'm-0 px-4.5 py-2.5 gap-2.5 bg-ink inline-flex items-center rounded-[999px] text-surface text-[16px] font-bold [--nala-ring:var(--color-ink)]',
  note: 'mx-0 mt-3 mb-0 max-w-[72ch] text-[13px] leading-[20px] text-text-secondary',
  grid: 'mt-6 gap-10 grid items-stretch grid-cols-[repeat(auto-fit,minmax(min(100%,440px),1fr))] max-md:gap-6 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:mt-4 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:gap-7',
  chip: 'px-3 py-1.5 inline-block self-start rounded-[999px] text-[13px] font-bold data-[tone=light]:bg-surface data-[tone=light]:text-primary-hover data-[tone=warm]:bg-warning-bg data-[tone=warm]:text-warning-text data-[tone=info]:bg-info-bg data-[tone=info]:text-primary-hover',
  panel: 'p-[clamp(24px,4vw,48px)] gap-10 min-h-110 bg-primary flex flex-col justify-between rounded-[32px] text-surface [&_h1]:mx-0 [&_h1]:mt-6 [&_h1]:mb-0 [&_h1]:text-balance [&_h1]:text-[clamp(32px,5vw,56px)] [&_h1]:leading-[1.15] [&_h1]:font-extrabold [&_h1]:tracking-[-.025em] [&_p]:mx-0 [&_p]:mt-4 [&_p]:mb-0 [&_p]:text-[17px] [&_p]:leading-[26px] [&_p]:text-[rgb(255_255_255_/_.88)] max-md:min-h-0 max-md:rounded-[24px] [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:p-9 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:gap-7 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:min-h-85 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:rounded-[28px] [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_h1]:text-[clamp(30px,3.4vw,44px)] [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_p]:text-[16px] [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_p]:leading-[24px]',
  startTitle: '[&_h1]:m-0 [&_h1]:text-balance [&_h1]:text-[clamp(32px,5vw,56px)] [&_h1]:leading-[1.15] [&_h1]:font-extrabold [&_h1]:tracking-[-.025em] gap-4 flex flex-col [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_h1]:text-[clamp(30px,3.4vw,44px)] [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_svg]:w-19 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_svg]:h-auto',
  waiting: 'px-6 py-5 gap-4 bg-primary-hover flex items-center rounded-[20px] [&_strong]:block [&_strong]:text-[18px] [&_strong]:font-extrabold [&_small]:mt-0.5 [&_small]:block [&_small]:text-[14px] [&_small]:text-[rgb(255_255_255_/_.88)] [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:px-5 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:py-4 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_strong]:text-[16px]',
  dot: 'w-3.5 h-3.5 flex-none bg-accent rounded-[50%]',
  warm: 'gap-5 min-w-0 flex flex-col justify-center [&_h2]:m-0 [&_h2]:text-[clamp(26px,4vw,40px)] [&_h2]:leading-[1.2] [&_h2]:font-extrabold [&_h2]:tracking-[-.02em] [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:gap-4 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_h2]:text-[clamp(24px,2.6vw,32px)] [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_svg]:w-19 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_svg]:h-auto',
  question: 'mx-0 -mt-2 mb-0 text-pretty text-ink text-[20px] leading-[30px] [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:text-[18px] [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:leading-[27px]',
  options: "gap-4 flex flex-col [&_button]:px-6 [&_button]:py-4 [&_button]:gap-4 [&_button]:w-full [&_button]:min-h-21 [&_button]:border-[3px] [&_button]:border-ink [&_button]:bg-accent [&_button]:flex [&_button]:items-center [&_button]:text-start [&_button]:rounded-[20px] [&_button]:text-ink [&_button]:[box-shadow:0_6px_0_var(--color-ink)] [&_button]:text-[20px] [&_button]:leading-[28px] [&_button]:font-bold [&_button]:[transition:transform_var(--motion-fast),box-shadow_var(--motion-fast)] [&_button[data-option='1']]:bg-primary [&_button[data-option='1']]:text-surface [&_button[data-option='2']]:[background:var(--lobby-orange)] [&_button:hover:not(:disabled)]:[filter:none] [&_button[aria-pressed=true]]:[transform:translateY(4px)] [&_button[aria-pressed=true]]:[box-shadow:0_2px_0_var(--color-ink)] [&_button>span:first-child]:w-11 [&_button>span:first-child]:h-11 [&_button>span:first-child]:flex-none [&_button>span:first-child]:border-[3px] [&_button>span:first-child]:border-ink [&_button>span:first-child]:bg-surface [&_button>span:first-child]:grid [&_button>span:first-child]:items-center [&_button>span:first-child]:justify-items-center [&_button>span:first-child]:rounded-[12px] [&_button>span:first-child]:text-ink [&_button>span:first-child]:text-[20px] [&_button>span:first-child]:font-extrabold [&_button>span:nth-child(2)]:min-w-0 [&_button>span:nth-child(2)]:flex-1 [&_button_svg]:p-1.5 [&_button_svg]:flex-none [&_button_svg]:bg-surface [&_button_svg]:box-content [&_button_svg]:rounded-[50%] [&_button_svg]:text-ink max-md:[&_button]:px-4 max-md:[&_button]:py-3 max-md:[&_button]:min-h-18 max-md:[&_button]:text-[18px] [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:gap-2.5 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_button]:px-5 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_button]:py-2.5 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_button]:min-h-15 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_button]:text-[18px]",
  hint: 'm-0 min-h-7 text-[16px] font-semibold text-text-secondary',
  preview: 'mt-8 px-5 py-4 gap-y-3 gap-x-4 border-dashed border border-control-border bg-surface flex flex-wrap items-center rounded-[14px] [&_p]:m-0 [&_p]:flex-[1_1_280px] [&_p]:text-[13px] [&_p]:leading-[20px] [&_p]:text-text-secondary',
  startHead: 'gap-6 flex flex-wrap items-end justify-between',
  ready: 'px-9 gap-2.5 min-h-16 border-[3px] border-ink rounded-[18px] [box-shadow:0_6px_0_var(--color-ink)] text-[20px] font-extrabold active:[transform:translateY(4px)] active:[box-shadow:0_2px_0_var(--color-ink)] [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:px-7 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:min-h-13.5 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:text-[18px]',
  steps: "mx-0 mt-10 mb-0 p-0 gap-6 grid list-none grid-cols-[repeat(auto-fit,minmax(min(100%,300px),1fr))] [&_li]:p-8 [&_li]:gap-8 [&_li]:min-h-70 [&_li]:bg-accent [&_li]:flex [&_li]:flex-col [&_li]:justify-between [&_li]:rounded-[28px] [&_li]:text-ink [&_li[data-step='1']]:bg-primary [&_li[data-step='1']]:text-surface [&_li[data-step='2']]:[background:var(--lobby-orange)] [&_li>span]:text-[96px] [&_li>span]:leading-[1] [&_li>span]:font-extrabold [&_li>span]:tracking-[-.04em] [&_h2]:m-0 [&_h2]:text-inherit [&_h2]:text-[28px] [&_h2]:leading-[34px] [&_h2]:font-extrabold [&_h2]:tracking-[-.015em] [&_p]:mx-0 [&_p]:mt-2 [&_p]:mb-0 [&_p]:text-inherit [&_p]:text-[17px] [&_p]:leading-[26px] max-md:[&_li]:p-6 max-md:[&_li]:min-h-0 max-md:[&_li>span]:text-[64px] [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:mt-7 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:gap-5 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_li]:p-6 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_li]:gap-5 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_li]:min-h-52.5 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_li]:rounded-[24px] [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_li>span]:text-[72px] [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_h2]:text-[24px] [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_h2]:leading-[30px] [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_p]:text-[16px] [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_p]:leading-[24px]",
  pills: 'mx-0 mt-10 mb-0 p-0 gap-3 flex flex-wrap list-none [&_li]:px-4 [&_li]:py-2.5 [&_li]:gap-2 [&_li]:border-2 [&_li]:border-ink [&_li]:bg-surface [&_li]:flex [&_li]:items-center [&_li]:rounded-[999px] [&_li]:text-[15px] [&_li]:font-bold [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:mt-7 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:gap-2.5 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_li]:px-3.5 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_li]:py-2 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_li]:text-[14px]',
  leaveLink: 'p-0 min-h-11 border-none self-start [font-style:inherit] underline cursor-pointer [background:none] text-inherit [font-variant:inherit] font-semibold [font-stretch:inherit] text-[14px] [line-height:inherit] [font-family:inherit] [text-underline-offset:3px]',
  leave: 'gap-y-2 gap-x-3 flex flex-wrap items-center text-[14px] leading-[22px] [&_p]:m-0 [&_p]:basis-full [&_p]:font-semibold [&_button]:px-4.5 [&_button]:py-0 [&_button]:min-h-11 [&_button]:border [&_button]:border-current [&_button]:[font-style:inherit] [&_button]:cursor-pointer [&_button]:rounded-[999px] [&_button]:[background:none] [&_button]:text-inherit [&_button]:[font-variant:inherit] [&_button]:font-bold [&_button]:[font-stretch:inherit] [&_button]:[font-size:inherit] [&_button]:[line-height:inherit] [&_button]:[font-family:inherit] [&_button:first-of-type]:border-ink [&_button:first-of-type]:bg-ink [&_button:first-of-type]:text-surface',
} satisfies Record<string, string>

export default styles
