// Tailwind classes for LiveStudentJoin.tsx.
// `studentjoin-*` names carry no styles: they are hooks for the nested selectors in other entries.
const styles = {
  // Supplied "Gabung dengan kode" screen (SK-1): the entry on the left, the blue reassurance panel on the right.
  page: 'min-h-[calc(100dvh_-_64px)] flex-1 grid [--join-error:#D2521F] [--join-shadow:#13266F] grid-cols-[repeat(auto-fit,minmax(min(100%,480px),1fr))] max-md:min-h-0 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:min-h-[calc(100dvh_-_56px)]',
  entry: 'p-16 gap-8 max-w-190 flex flex-col justify-center max-md:px-4 max-md:py-8 max-md:gap-6 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:px-12 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:py-7 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:gap-5',
  back: '-mb-4 py-1 pr-4.5 pl-1.5 gap-2 min-h-11 border-2 border-ink bg-surface inline-flex items-center self-start no-underline rounded-[999px] text-ink text-[15px] font-bold hover:bg-warning-bg',
  arrow: 'w-7.5 h-7.5 flex-none bg-ink grid items-center justify-items-center rounded-[50%] text-surface',
  intro: 'gap-4 flex flex-col items-start [&_h1]:m-0 [&_h1]:text-balance [&_h1]:text-[clamp(32px,5vw,56px)] [&_h1]:leading-[1.15] [&_h1]:font-extrabold [&_h1]:tracking-[-.025em] [&_p]:m-0 [&_p]:text-[18px] [&_p]:leading-[28px] [&_p]:text-text-secondary [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:gap-3 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_svg]:w-22 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_svg]:h-auto [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_h1]:text-[clamp(30px,3vw,38px)] [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_p]:text-[16px] [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&_p]:leading-[24px]',
  chip: 'px-3 py-1.5 bg-warning-bg rounded-[999px] text-warning-text text-[13px] font-bold',
  code: 'studentjoin-code max-w-140 relative focus-within:[outline:3px_solid_var(--color-primary)] focus-within:outline-offset-[8px] focus-within:rounded-[20px] [&_input]:m-0 [&_input]:p-0 [&_input]:inset-0 [&_input]:w-full [&_input]:h-full [&_input]:border-none [&_input]:absolute [&_input]:cursor-text [&_input]:opacity-0 [&_input]:text-[16px] [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:max-w-110',
  boxes: 'gap-3 grid grid-cols-6 [&>span]:border-[3px] [&>span]:border-ink [&>span]:bg-surface [&>span]:flex [&>span]:items-center [&>span]:justify-center [&>span]:aspect-[5/6] [&>span]:rounded-[16px] [&>span]:text-ink [&>span]:[box-shadow:0_6px_0_var(--color-ink)] [&>span]:text-[clamp(28px,6vw,44px)] [&>span]:font-extrabold [&>span]:[transition:background_.25s,color_.25s] [&>span[data-filled=true]]:bg-warning-bg [.studentjoin-code[data-state=wrong]_&>span]:[border-color:var(--join-error)] [.studentjoin-code[data-state=wrong]_&>span]:[box-shadow:0_6px_0_var(--join-error)] [.studentjoin-code[data-state=joined]_&>span]:bg-success-text [.studentjoin-code[data-state=joined]_&>span]:text-surface [.studentjoin-code[data-state=joined]_&>span]:[animation:studentjoin-wave_.5s_cubic-bezier(.2,.8,.2,1)_backwards] motion-reduce:[.studentjoin-code[data-state=joined]_&>span]:[animation:none] max-md:gap-2 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:gap-2.5 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:[&>span]:text-[clamp(26px,3vw,34px)]',
  char: '[animation:studentjoin-pop_.35s_cubic-bezier(.2,.8,.2,1)] motion-reduce:[animation:none]',
  caret: 'w-[3px] h-10 bg-primary rounded-[2px] [animation:studentjoin-caret_1s_steps(1)_infinite] motion-reduce:[animation:none] [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:h-8',
  message: 'm-0 min-h-6 text-[16px] font-semibold data-[tone=ok]:text-success-text data-[tone=error]:text-misconception-text',
  actions: 'gap-6 flex flex-wrap items-center',
  enter: 'px-8 py-0 gap-2 h-15 border-none bg-primary flex items-center rounded-[16px] text-surface [box-shadow:0_6px_0_var(--join-shadow)] text-[18px] font-extrabold hover:bg-[#1F40C2] active:[transform:translateY(4px)] active:[box-shadow:0_2px_0_var(--join-shadow)] [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:px-7 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:py-0 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:h-13 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:text-[16px]',
  demo: 'p-0 min-h-11 border-none underline [background:none] text-primary text-[15px] font-semibold [text-underline-offset:4px] hover:not-disabled:[background:none] hover:not-disabled:text-primary-hover',
  panel: 'm-6 p-14 gap-12 min-h-140 bg-primary flex flex-col justify-between rounded-[32px] text-surface max-md:m-4 max-md:px-6 max-md:py-8 max-md:gap-8 max-md:min-h-0 max-md:rounded-[24px] [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:m-4 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:p-9 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:gap-8 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:min-h-0 [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:rounded-[28px]',
  kicker: 'text-[15px] font-bold text-[#DCE3F7]',
  big: 'm-0 gap-2 flex flex-col text-inherit text-[clamp(30px,4vw,48px)] leading-[1.17] font-extrabold tracking-[-.025em] [&_span:last-child]:text-accent [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:text-[clamp(28px,2.8vw,36px)]',
  small: 'm-0 max-w-110 text-[17px] leading-[26px] text-[#DCE3F7] [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:text-[15px] [@media(min-width:768px)_and_(max-width:1599px),_(min-width:768px)_and_(max-height:899px)]:leading-[23px]',
} satisfies Record<string, string>

export default styles
