// Tailwind classes for StudentStartPage.tsx.
const styles = {
  content: 'mx-auto max-w-262.5',
  back: 'mb-3 gap-1.5 min-h-11 inline-flex items-center no-underline text-[13px] font-semibold text-text-secondary hover:text-primary',
  header: 'mb-6 gap-5 flex flex-wrap items-center justify-between [&>div]:flex-[1_1_350px] [&_p]:mx-0 [&_p]:mt-2.5 [&_p]:mb-0 [&_p]:text-[13px] [&_p]:text-text-secondary [&>button]:px-6 [&>button]:min-h-12 [&>button]:text-[15px] [&>button]:[transition:transform_140ms_cubic-bezier(.23,1,.32,1),background-color_140ms_ease] [&>a]:px-6 [&>a]:min-h-12 [&>a]:text-[15px] [&>a]:[transition:transform_140ms_cubic-bezier(.23,1,.32,1),background-color_140ms_ease] [&>button:active:not(:disabled)]:[transform:scale(.98)] [&>a:active]:[transform:scale(.98)] [@media(max-width:700px)]:[&>button]:w-full [@media(max-width:700px)]:[&>a]:w-full motion-reduce:[&>button]:[transition:none] motion-reduce:[&>a]:[transition:none] motion-reduce:[&>button:active:not(:disabled)]:[transform:none] motion-reduce:[&>a:active]:[transform:none]',
  titleRow: 'gap-2.5 flex flex-col-reverse items-start [&_h1]:m-0 [&_h1]:text-balance [&_h1]:text-[clamp(26px,3vw,34px)] [&_h1]:leading-[1.3] [&_h1]:tracking-[-.03em] [&_span]:px-2.5 [&_span]:py-1 [&_span]:bg-info-bg [&_span]:rounded-[6px] [&_span]:text-primary-hover [&_span]:text-[12px] [&_span]:font-bold',
  welcome: 'px-8 py-6 gap-5 bg-warning-bg flex items-center justify-between rounded-student-card [&_h2]:m-0 [&_h2]:text-[24px] [&_h2]:leading-[1.3] [&_h2]:tracking-[-.025em] [&_p]:mx-0 [&_p]:mt-3 [&_p]:mb-0 [&_p]:max-w-[48ch] [&_p]:font-reading [&_p]:text-[18px] [&_p]:leading-[1.5] [&_p]:text-warning-text [@media(max-width:700px)]:p-6 [@media(max-width:700px)]:gap-0 [@media(max-width:700px)]:flex-wrap [@media(max-width:700px)]:[&_svg]:ml-auto [@media(max-width:700px)]:[&_svg]:w-27 [@media(max-width:700px)]:[&_svg]:h-auto [@media(max-width:700px)]:[&_h2]:text-[24px] [@media(max-width:700px)]:[&_p]:text-[17px]',
  stats: 'mx-0 my-6 p-0 grid list-none grid-cols-3 [&_li]:px-5 [&_li]:py-3 [&_li]:gap-y-1 [&_li]:gap-x-2.5 [&_li]:[border-left-style:solid] [&_li]:border-l [&_li]:border-l-border [&_li]:grid [&_li]:grid-cols-[24px_minmax(0,1fr)] [&_li:first-child]:pl-0 [&_li:first-child]:border-none [&_li:first-child]:border-0 [&_li:first-child]:border-current [&_svg]:mt-0.5 [&_svg]:row-[1_/_3] [&_svg]:text-primary-hover [&_strong]:text-[14px] [&_strong]:font-semibold [&_small]:text-[12px] [&_small]:text-text-secondary [@media(max-width:700px)]:gap-2 [@media(max-width:700px)]:grid-cols-[minmax(0,1fr)] [@media(max-width:700px)]:[&_li]:px-0 [@media(max-width:700px)]:[&_li]:py-2 [@media(max-width:700px)]:[&_li]:border-none [@media(max-width:700px)]:[&_li]:border-0 [@media(max-width:700px)]:[&_li]:border-current',
  grid: 'gap-6 grid grid-cols-[minmax(0,1.15fr)_minmax(0,1fr)] [@media(max-width:700px)]:grid-cols-[minmax(0,1fr)]',
  card: 'p-7 min-w-0 border border-border bg-surface rounded-student-card [&_h2]:m-0 [&_h2]:text-[19px] [&_h2]:leading-[1.4] [&_h2]:tracking-[-.02em] [&_ol]:mx-0 [&_ol]:mt-6 [&_ol]:mb-0 [&_ol]:p-0 [&_ol]:gap-6 [&_ol]:grid [&_ol]:list-none [&_li]:gap-3.5 [&_li]:flex [&_li]:items-start [&_li>span]:w-8.5 [&_li>span]:h-8.5 [&_li>span]:flex-none [&_li>span]:bg-info-bg [&_li>span]:grid [&_li>span]:items-center [&_li>span]:justify-items-center [&_li>span]:rounded-[10px] [&_li>span]:text-primary-hover [&_li>span]:text-[14px] [&_li>span]:font-bold [&_strong]:mb-1 [&_strong]:block [&_strong]:text-[14px] [&_small]:block [&_small]:font-reading [&_small]:text-[15px] [&_small]:leading-[1.5] [&_small]:text-text-secondary [@media(max-width:700px)]:p-6',
  notes: 'p-7 min-w-0 border border-border bg-paper rounded-student-card [--nala-ring:var(--color-paper)] [&_h2]:m-0 [&_h2]:text-[19px] [&_h2]:leading-[1.4] [&_h2]:tracking-[-.02em] [&_h2_small]:mt-[3px] [&_h2_small]:block [&_h2_small]:text-[12px] [&_h2_small]:font-medium [&_h2_small]:text-text-secondary [&_ul]:mx-0 [&_ul]:mt-6 [&_ul]:mb-0 [&_ul]:pl-4.5 [&_ul]:gap-4 [&_ul]:grid [&_li]:pl-1 [&_li]:font-reading [&_li]:text-[16px] [&_li]:leading-[1.5] [&_li]:text-text-secondary [&_li::marker]:text-warning-text [@media(max-width:700px)]:p-6',
  notesHead: 'gap-3 flex items-center [&>svg]:text-warning-text',
} satisfies Record<string, string>

export default styles
